"""Practical skill-test question banks. Each test is 5 MCQs.
Answers are real-world / scenario-based, not theory."""

SKILL_TESTS = {
    "Plumber": [
        {"q": "A tap is leaking from the spout (not the joint) even when fully closed. What is the most likely fix?",
         "options": ["Tighten the wall flange", "Replace the washer / cartridge inside the tap", "Replace the whole tap", "Apply more PTFE tape on the inlet"],
         "answer": 1},
        {"q": "You smell sewage from a kitchen sink that's been unused for a week. First action?",
         "options": ["Pour acid down the drain", "Run water for 30 seconds to refill the dry P-trap", "Replace the entire drain pipe", "Open the wall to check"],
         "answer": 1},
        {"q": "Hot water in the bathroom is brown for the first 10 seconds. Why?",
         "options": ["The geyser heating coil is broken", "Rust / sediment in the geyser tank — needs flushing", "The cold inlet is clogged", "Wrong type of pipe"],
         "answer": 1},
        {"q": "Customer wants a new shower head fitted. What do you do BEFORE removing the old one?",
         "options": ["Shut off the water supply at the angle valve / main", "Drain the geyser", "Cover the floor with newspaper", "Call the plumber"],
         "answer": 0},
        {"q": "Threaded brass joint is leaking after you tightened it. Best next step?",
         "options": ["Tighten it 2 more turns hard", "Open it, clean threads, wrap fresh PTFE tape clockwise, re-tighten by hand + 1-2 turns", "Apply M-Seal on outside", "Replace the brass elbow"],
         "answer": 1},
    ],
    "Electrician": [
        {"q": "A switch sparks slightly when turned on. What's the safest first action?",
         "options": ["Turn off the MCB for that circuit and inspect the switch", "Tape the switch with electrical tape", "Replace the bulb", "Ignore it"],
         "answer": 0},
        {"q": "A 3-pin socket has only 2 wires connected (live + neutral, no earth). Risk?",
         "options": ["None, the appliance still works", "Shock risk on metal-body appliances — earth must be connected", "Higher electricity bill", "Bulb flickering"],
         "answer": 1},
        {"q": "Customer says lights dim every time the fridge starts. Most likely cause?",
         "options": ["Bulbs are too old", "Loose neutral or undersized cable on that line", "AC voltage is low everywhere", "MCB is wrong rating"],
         "answer": 1},
        {"q": "You need to drill into a wall to fit a switch board. Before drilling, what do you check?",
         "options": ["Wall colour", "Whether there are existing live wires or pipes behind using a detector / tap pattern", "Drill bit size only", "Customer's mood"],
         "answer": 1},
        {"q": "MCB keeps tripping immediately when turned ON, even with all appliances unplugged. Likely cause?",
         "options": ["MCB rating too high", "Short circuit somewhere in the wiring on that line", "Voltage fluctuation", "MCB is too new"],
         "answer": 1},
    ],
    "Painter": [
        {"q": "Old wall has flaking paint. What MUST you do before applying new paint?",
         "options": ["Paint directly over it", "Scrape off loose paint, sand, fill cracks with putty, apply primer", "Just apply 2 coats", "Wash with soap only"],
         "answer": 1},
        {"q": "Customer wants a dark wall colour over an existing white wall. Best approach?",
         "options": ["1 coat is enough", "Apply tinted primer + 2 coats of finish for proper coverage", "Mix water in paint", "Paint at night"],
         "answer": 1},
        {"q": "Paint dries with brush marks on enamel finish. Likely reason?",
         "options": ["Paint is too thinned", "Brush was overloaded / wrong brush / paint not thinned enough", "Wall was too cold", "Wrong day"],
         "answer": 1},
        {"q": "There's a small damp patch on the ceiling. Should you paint over it?",
         "options": ["Yes, immediately with 2 coats", "No — find and fix the water source first, dry, treat with anti-damp primer", "Cover with thick putty only", "Use oil paint over it"],
         "answer": 1},
        {"q": "Estimate paint needed: room walls 100 sq ft, 2 coats. Coverage ~120 sq ft per litre per coat. You need approximately?",
         "options": ["0.5 litre", "1.7 litres (~2 litres)", "5 litres", "10 litres"],
         "answer": 1},
    ],
    "Mason": [
        {"q": "Standard cement:sand ratio for plastering an interior wall?",
         "options": ["1:1", "1:6 (one part cement, six parts sand)", "1:20", "Only cement"],
         "answer": 1},
        {"q": "Fresh plaster started cracking the next day. Most likely reason?",
         "options": ["Too much sand and not enough curing (water sprinkling)", "Wall was painted underneath", "Customer touched it", "Cement was too new"],
         "answer": 0},
        {"q": "Customer wants a brick wall built straight. What do you use to keep it true?",
         "options": ["Eye estimation only", "Plumb line, spirit level and string line", "Just the trowel", "Brick weight"],
         "answer": 1},
        {"q": "How long should fresh concrete be cured (water-sprinkled) at minimum?",
         "options": ["1 hour", "At least 7 days, ideally 14-21 days", "1 month always", "No need to cure"],
         "answer": 1},
        {"q": "You see efflorescence (white powder) on a finished wall. What is it?",
         "options": ["Mold", "Salt deposits — usually from moisture in masonry, can be brushed off, but the source needs fixing", "Cement leak", "Paint reaction"],
         "answer": 1},
    ],
    "Carpenter": [
        {"q": "Customer wants a wardrobe in a humid coastal area. Best material?",
         "options": ["MDF (cheapest)", "Marine ply or BWP grade plywood", "Particle board", "Plain pine"],
         "answer": 1},
        {"q": "A wooden door is sticking in monsoon. Why?",
         "options": ["Hinges are old", "Wood absorbs moisture and swells — plane and seal the edges", "Door is too heavy", "Lock is bad"],
         "answer": 1},
        {"q": "Best way to join two pieces of plywood at a right angle for a kitchen cabinet?",
         "options": ["Nails only", "Wood glue + screws (or dowels) for strong joint", "Tape", "Plain push fit"],
         "answer": 1},
        {"q": "You are about to cut a 15mm plywood sheet. Which side should face UP when using a circular saw to get a clean cut?",
         "options": ["Doesn't matter", "Good/finish side facing DOWN (circular saw chips on the top side)", "Both sides face up", "Cut without thinking"],
         "answer": 1},
        {"q": "Customer wants soft-close hinges for kitchen shutters. What do you check before installing?",
         "options": ["Shutter colour", "Shutter weight + cabinet thickness — hinge must be rated for the load", "Brand only", "Customer's height"],
         "answer": 1},
    ],
    "Driver": [
        {"q": "While driving, a child suddenly runs onto the road 20 metres ahead. Correct action?",
         "options": ["Honk and continue at the same speed", "Brake hard and check rear-view mirror; swerve only if rear is clear and no oncoming traffic", "Speed up to pass before the child reaches", "Close your eyes"],
         "answer": 1},
        {"q": "Your car starts vibrating at high speed only. Most likely cause?",
         "options": ["Engine oil is too dark", "Wheel imbalance or alignment issue", "Wrong fuel", "Tyre colour"],
         "answer": 1},
        {"q": "You are at a 4-way junction with no signal and no traffic cop. Who goes first?",
         "options": ["Whoever honks louder", "Vehicle on your right has right of way (in India)", "Biggest vehicle", "Slowest vehicle"],
         "answer": 1},
        {"q": "Engine temperature warning light comes on. Correct response?",
         "options": ["Switch off AC, find safe spot, stop, let engine cool, check coolant — never open hot radiator", "Continue driving, it will reset", "Pour water from a bottle while driving", "Ignore it"],
         "answer": 0},
        {"q": "Driving in heavy rain at night with low visibility. Lights to use?",
         "options": ["High beam (most light)", "Low beam + fog lamps if fitted; never high beam (reflects off rain back into your eyes)", "Hazard lights while moving", "Headlights off"],
         "answer": 1},
    ],
    "Helper": [
        {"q": "Senior worker asks you to fetch a 2-metre PVC pipe + elbow. You bring only the pipe. What should you do?",
         "options": ["Wait silently", "Go back and bring the elbow too — listen to the full instruction the first time", "Argue", "Bring a different fitting"],
         "answer": 1},
        {"q": "You are carrying cement bags up a staircase. Safest way?",
         "options": ["Carry 3 at a time to save trips", "Carry 1 at a time, lift with legs (not back), keep one hand free for railing", "Drag them up", "Throw them up"],
         "answer": 1},
        {"q": "Plumber is in the middle of fitting a joint. He needs the spanner he set down. You should...",
         "options": ["Tell him to get it himself", "Pick it up and hand it to him handle-first without him asking", "Hide it as a joke", "Wait until he calls"],
         "answer": 1},
        {"q": "At a worksite you notice an exposed live wire on the floor. First step?",
         "options": ["Touch it to check", "Warn everyone, switch off the MCB or call the electrician — do not touch", "Cover with cloth", "Ignore"],
         "answer": 1},
        {"q": "End of day at a site. The senior leaves first. You should...",
         "options": ["Leave immediately too", "Clean up tools, sweep debris, lock up, then leave — a clean site is a sign of a good helper", "Take a tool home", "Sleep there"],
         "answer": 1},
    ],
    "AC Technician": [
        {"q": "Split AC is running but not cooling. The outdoor unit fan is OFF. Most likely cause?",
         "options": ["Wrong remote", "Capacitor failure or compressor relay issue in the outdoor unit", "Filter dirty", "Voltage too high"],
         "answer": 1},
        {"q": "Customer says window AC is leaking water inside the room. Most common cause?",
         "options": ["Refrigerant leak", "Drain pipe blocked or AC tilted wrong way (must tilt slightly DOWN towards the outside)", "Compressor broken", "Wrong remote"],
         "answer": 1},
        {"q": "Before opening any AC indoor unit panel for service, what MUST you do?",
         "options": ["Remove the remote battery", "Switch off the AC at the power socket / MCB", "Wear sunglasses", "Take a photo"],
         "answer": 1},
        {"q": "Customer wants to know why their AC suddenly uses much more electricity. Common reason?",
         "options": ["AC is new", "Dirty filter / dirty outdoor coil + low refrigerant — compressor runs longer", "Remote is old", "Room is small"],
         "answer": 1},
        {"q": "After gas top-up, the AC cools fine but stops cooling 1 week later. What does this indicate?",
         "options": ["Normal behaviour", "There is a refrigerant leak — find and fix the leak, don't just refill again", "AC is too small", "Customer is wrong"],
         "answer": 1},
    ],
}
