import { createContext, useContext, useState } from "react";

const STRINGS = {
  en: {
    appName: "Rozgar Mitra", tagline: "Trusted work, fair pay",
    login: "Login", register: "Register", username: "Username", password: "Password",
    name: "Full Name", phone: "Phone", city: "City", area: "Area / Locality",
    skill: "Skill", experience: "Years of Experience", company: "Company Name",
    iAmA: "I am a", worker: "Worker", employer: "Employer", continue: "Continue",
    demoAccounts: "Demo Accounts (tap to switch)",
    search: "Search Jobs", active: "Active", pending: "Pending", invites: "Invites",
    postJob: "Post Job", myJobs: "My Jobs", workers: "Workers", activeJobs: "Active Jobs",
    profile: "Profile", history: "Work History", reviews: "Reviews", logout: "Logout",
    availability: "I am available for work", urgentNow: "I'm available RIGHT NOW",
    urgentActive: "🟢 LIVE — 8 hour pulse active",
    yourPassport: "Your Work Passport",
    reliabilityScore: "Reliability Score", verifiedJobs: "Verified Jobs",
    avgRating: "Avg Rating", totalEarned: "Total Earned", uniqueEmployers: "Unique Employers",
    repeatEmployers: "Repeat Employers", completionRate: "Completion Rate",
    shareWhatsApp: "Share on WhatsApp",
    applyNow: "Apply Now", applied: "Applied", spotsLeft: "spots left",
    deadline: "Deadline", budget: "Budget", noJobs: "No open jobs match your filters yet.",
    filterBySkill: "Filter by skill", allSkills: "All skills",
    searchPlaceholder: "Search by title or city...",
    employerProfile: "Employer", trusted: "Trusted",
    waitingForDecision: "Waiting for employer...", withdraw: "Withdraw",
    goToActive: "Go to Active Job", confirmed: "Confirmed", rejected: "Not selected this time",
    noPending: "No pending applications.", noInvites: "No invites yet.",
    accept: "Accept", decline: "Decline", invitedFor: "Invited for",
    activeJobTitle: "Your Current Job", callEmployer: "Call Employer",
    uploadPhoto: "Upload Work Photo", takeSelfie: "Take site selfie",
    markComplete: "Mark Job Complete", rateEmployer: "Rate Employer",
    quickTags: "Quick Tags", reviewText: "Anything else? (optional)",
    submit: "Submit", noActiveJob: "You have no active job right now.",
    findWork: "Find Work",
    title: "Job Title", description: "Description", address: "Full Address",
    workersNeeded: "Workers Needed", postJobCta: "Post the Job",
    applicants: "Applicants", hire: "Hire", pass: "Pass", hired: "Hired",
    noApplicants: "No applicants yet.",
    browseWorkers: "Browse Workers", sendInvite: "Send Invite for...",
    completeReview: "Complete & Review", noActiveEmp: "No active jobs.",
    aadhaarVerified: "Aadhaar Verified",
    jobsPosted: "Jobs Posted", jobsCompleted: "Jobs Completed",
    backToList: "Back",
    languageToggle: "हिं/EN",
    youAreOffline: "You are hidden from employers",
    youAreOnline: "You are visible to employers",
    confirmHire: "Hire this worker?",
    photoSaved: "Photo saved", thanks: "Thank you!",
    safeWorkplace: "Safe workplace", fairPayment: "Fair payment", onTime: "Pays on time", respectful: "Respectful",
    skilled: "Skilled", punctual: "Punctual",     polite: "Polite", neatWork: "Neat work",
    viewHistory: "View History", pastWork: "Past Work",
    employerHistory: "Jobs Posted", noHistory: "No history yet.",
    reviewsFromWorkers: "Reviews from Workers",
    viewEmployer: "View Employer Profile",
    viewProfile: "View Profile",
    enableNotifications: "Enable Notifications",
    notificationsBlocked: "Blocked — enable in browser settings",
    offerReceived: "Employer wants to hire you!",
    acceptOffer: "Accept Job",
    declineOffer: "Decline",
    awaitingWorker: "Awaiting worker confirmation",
    rejectedByWorker: "Worker declined",
    remove: "Remove",
    waitingForWorker: "Waiting for worker to accept...",
  },
  hi: {
    appName: "रोज़गार मित्र", tagline: "भरोसेमंद काम, सही दाम",
    login: "लॉग इन", register: "रजिस्टर", username: "यूज़रनेम", password: "पासवर्ड",
    name: "पूरा नाम", phone: "फ़ोन", city: "शहर", area: "क्षेत्र",
    skill: "हुनर", experience: "अनुभव (साल)", company: "कंपनी का नाम",
    iAmA: "मैं हूँ", worker: "कारीगर", employer: "नियोक्ता", continue: "आगे बढ़ें",
    demoAccounts: "डेमो अकाउंट (तेज़ी से बदलें)",
    search: "काम ढूँढें", active: "चालू", pending: "बकाया", invites: "बुलावे",
    postJob: "काम डालें", myJobs: "मेरे काम", workers: "कारीगर", activeJobs: "चालू काम",
    profile: "प्रोफाइल", history: "काम का इतिहास", reviews: "रेटिंग", logout: "बाहर निकलें",
    availability: "मैं काम के लिए उपलब्ध हूँ", urgentNow: "मैं अभी फ्री हूँ",
    urgentActive: "🟢 लाइव — 8 घंटे की पल्स चालू",
    yourPassport: "आपका वर्क पासपोर्ट",
    reliabilityScore: "विश्वास स्कोर", verifiedJobs: "सत्यापित काम",
    avgRating: "औसत रेटिंग", totalEarned: "कुल कमाई", uniqueEmployers: "नियोक्ता",
    repeatEmployers: "बार-बार बुलाने वाले", completionRate: "पूर्ण करने की दर",
    shareWhatsApp: "व्हाट्सएप पर शेयर करें",
    applyNow: "अभी आवेदन करें", applied: "आवेदन किया", spotsLeft: "जगह बाकी",
    deadline: "अंतिम तिथि", budget: "मेहनताना", noJobs: "अभी कोई काम नहीं मिला।",
    filterBySkill: "हुनर से छाँटें", allSkills: "सभी हुनर",
    searchPlaceholder: "टाइटल या शहर से खोजें...",
    employerProfile: "नियोक्ता", trusted: "भरोसेमंद",
    waitingForDecision: "नियोक्ता के जवाब का इंतज़ार...", withdraw: "वापस लें",
    goToActive: "चालू काम पर जाएँ", confirmed: "स्वीकार", rejected: "इस बार नहीं चुने गए",
    noPending: "कोई बकाया आवेदन नहीं।", noInvites: "अभी कोई बुलावा नहीं।",
    accept: "स्वीकार करें", decline: "मना करें", invitedFor: "इस काम के लिए बुलावा",
    activeJobTitle: "आपका मौजूदा काम", callEmployer: "नियोक्ता को कॉल करें",
    uploadPhoto: "काम की फ़ोटो डालें", takeSelfie: "साइट पर सेल्फी लें",
    markComplete: "काम पूरा हुआ", rateEmployer: "नियोक्ता को रेट करें",
    quickTags: "त्वरित टैग", reviewText: "और कुछ कहना है? (वैकल्पिक)",
    submit: "भेजें", noActiveJob: "अभी कोई चालू काम नहीं।",
    findWork: "काम ढूँढें",
    title: "काम का नाम", description: "विवरण", address: "पूरा पता",
    workersNeeded: "कारीगरों की संख्या", postJobCta: "काम डालें",
    applicants: "आवेदक", hire: "रखें", pass: "छोड़ें", hired: "रखा गया",
    noApplicants: "अभी कोई आवेदक नहीं।",
    browseWorkers: "कारीगर देखें", sendInvite: "बुलावा भेजें...",
    completeReview: "पूरा करें और रेट करें", noActiveEmp: "कोई चालू काम नहीं।",
    aadhaarVerified: "आधार सत्यापित",
    jobsPosted: "डाले गए काम", jobsCompleted: "पूरे किए गए",
    backToList: "वापस",
    languageToggle: "हिं/EN",
    youAreOffline: "आप नियोक्ताओं से छुपे हैं",
    youAreOnline: "आप नियोक्ताओं को दिख रहे हैं",
    confirmHire: "इस कारीगर को रखें?",
    photoSaved: "फ़ोटो सेव हुई", thanks: "धन्यवाद!",
    safeWorkplace: "सुरक्षित जगह", fairPayment: "सही भुगतान", onTime: "समय पर भुगतान",
    respectful: "सम्मानजनक", skilled: "हुनरमंद", punctual: "समय का पाबंद",
    polite: "विनम्र", neatWork: "साफ काम",
    viewHistory: "इतिहास देखें", pastWork: "पिछला काम",
    employerHistory: "डाले गए काम", noHistory: "अभी कोई इतिहास नहीं।",
    reviewsFromWorkers: "कारीगरों की राय",
    viewEmployer: "नियोक्ता प्रोफाइल देखें",
    viewProfile: "प्रोफाइल देखें",
    enableNotifications: "नोटिफिकेशन चालू करें",
    notificationsBlocked: "ब्लॉक — ब्राउज़र सेटिंग से चालू करें",
    offerReceived: "नियोक्ता आपको रखना चाहता है!",
    acceptOffer: "काम स्वीकार करें",
    declineOffer: "मना करें",
    awaitingWorker: "कारीगर की पुष्टि का इंतज़ार",
    rejectedByWorker: "कारीगर ने मना किया",
    remove: "हटाएँ",
    waitingForWorker: "कारीगर के स्वीकार का इंतज़ार...",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("rm_lang") || "en");
  const toggle = () => {
    const next = lang === "en" ? "hi" : "en";
    localStorage.setItem("rm_lang", next);
    setLang(next);
  };
  const t = STRINGS[lang];
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>{children}</LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
