import { createContext, useContext, useState } from "react";

// Metadata for every supported language: code, native-script label
// (shown in the picker), and English label (for search/accessibility).
export const LANGUAGES = [
  { code: "en", native: "English", english: "English" },
  { code: "hi", native: "हिन्दी", english: "Hindi" },
  { code: "bn", native: "বাংলা", english: "Bengali" },
  { code: "mr", native: "मराठी", english: "Marathi" },
  { code: "te", native: "తెలుగు", english: "Telugu" },
  { code: "ta", native: "தமிழ்", english: "Tamil" },
  { code: "gu", native: "ગુજરાતી", english: "Gujarati" },
  { code: "ur", native: "اردو", english: "Urdu" },
  { code: "kn", native: "ಕನ್ನಡ", english: "Kannada" },
  { code: "or", native: "ଓଡ଼ିଆ", english: "Odia" },
  { code: "pa", native: "ਪੰਜਾਬੀ", english: "Punjabi" },
  { code: "ml", native: "മലയാളം", english: "Malayalam" },
  { code: "as", native: "অসমীয়া", english: "Assamese" },
];

const STRINGS = {
  en: {
    appName: "Rozgar Mitra",
    tagline: "Trusted work, fair pay",
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    name: "Full Name",
    phone: "Phone",
    city: "City",
    area: "Area / Locality",
    skill: "Skill",
    experience: "Years of Experience",
    company: "Company Name",
    iAmA: "I am a",
    worker: "Worker",
    employer: "Employer",
    continue: "Continue",
    demoAccounts: "Demo Accounts (tap to switch)",
    search: "Search Jobs",
    active: "Active",
    pending: "Pending",
    invites: "Invites",
    postJob: "Post Job",
    myJobs: "My Jobs",
    workers: "Workers",
    activeJobs: "Active Jobs",
    profile: "Profile",
    history: "Work History",
    reviews: "Reviews",
    logout: "Logout",
    availability: "I am available for work",
    urgentNow: "I'm available RIGHT NOW",
    urgentActive: "🟢 LIVE — 8 hour pulse active",
    yourPassport: "Your Work Passport",
    reliabilityScore: "Reliability Score",
    verifiedJobs: "Verified Jobs",
    avgRating: "Avg Rating",
    totalEarned: "Total Earned",
    uniqueEmployers: "Unique Employers",
    repeatEmployers: "Repeat Employers",
    completionRate: "Completion Rate",
    shareWhatsApp: "Share on WhatsApp",
    applyNow: "Apply Now",
    applied: "Applied",
    spotsLeft: "spots left",
    deadline: "Deadline",
    budget: "Budget",
    noJobs: "No open jobs match your filters yet.",
    filterBySkill: "Filter by skill",
    allSkills: "All skills",
    searchPlaceholder: "Search by title or city...",
    employerProfile: "Employer",
    trusted: "Trusted",
    waitingForDecision: "Waiting for employer...",
    withdraw: "Withdraw",
    goToActive: "Go to Active Job",
    confirmed: "Confirmed",
    rejected: "Not selected this time",
    noPending: "No pending applications.",
    noInvites: "No invites yet.",
    accept: "Accept",
    decline: "Decline",
    invitedFor: "Invited for",
    activeJobTitle: "Your Current Job",
    callEmployer: "Call Employer",
    uploadPhoto: "Upload Work Photo",
    takeSelfie: "Take site selfie",
    markComplete: "Mark Job Complete",
    rateEmployer: "Rate Employer",
    quickTags: "Quick Tags",
    reviewText: "Anything else? (optional)",
    submit: "Submit",
    noActiveJob: "You have no active job right now.",
    findWork: "Find Work",
    title: "Job Title",
    description: "Description",
    address: "Full Address",
    workersNeeded: "Workers Needed",
    postJobCta: "Post the Job",
    applicants: "Applicants",
    hire: "Hire",
    pass: "Pass",
    hired: "Hired",
    noApplicants: "No applicants yet.",
    browseWorkers: "Browse Workers",
    sendInvite: "Send Invite for...",
    completeReview: "Complete & Review",
    noActiveEmp: "No active jobs.",
    aadhaarVerified: "Aadhaar Verified",
    jobsPosted: "Jobs Posted",
    jobsCompleted: "Jobs Completed",
    backToList: "Back",
    languageToggle: "Language",
    youAreOffline: "You are hidden from employers",
    youAreOnline: "You are visible to employers",
    confirmHire: "Hire this worker?",
    photoSaved: "Photo saved",
    thanks: "Thank you!",
    safeWorkplace: "Safe workplace",
    fairPayment: "Fair payment",
    onTime: "Pays on time",
    respectful: "Respectful",
    skilled: "Skilled",
    punctual: "Punctual",
    polite: "Polite",
    neatWork: "Neat work",
  },
  hi: {
    appName: "रोज़गार मित्र",
    tagline: "भरोसेमंद काम, सही दाम",
    login: "लॉग इन",
    register: "रजिस्टर",
    username: "यूज़रनेम",
    password: "पासवर्ड",
    name: "पूरा नाम",
    phone: "फ़ोन",
    city: "शहर",
    area: "क्षेत्र",
    skill: "हुनर",
    experience: "अनुभव (साल)",
    company: "कंपनी का नाम",
    iAmA: "मैं हूँ",
    worker: "कारीगर",
    employer: "नियोक्ता",
    continue: "आगे बढ़ें",
    demoAccounts: "डेमो अकाउंट (तेज़ी से बदलें)",
    search: "काम ढूँढें",
    active: "चालू",
    pending: "बकाया",
    invites: "बुलावे",
    postJob: "काम डालें",
    myJobs: "मेरे काम",
    workers: "कारीगर",
    activeJobs: "चालू काम",
    profile: "प्रोफाइल",
    history: "काम का इतिहास",
    reviews: "रेटिंग",
    logout: "बाहर निकलें",
    availability: "मैं काम के लिए उपलब्ध हूँ",
    urgentNow: "मैं अभी फ्री हूँ",
    urgentActive: "🟢 लाइव — 8 घंटे की पल्स चालू",
    yourPassport: "आपका वर्क पासपोर्ट",
    reliabilityScore: "विश्वास स्कोर",
    verifiedJobs: "सत्यापित काम",
    avgRating: "औसत रेटिंग",
    totalEarned: "कुल कमाई",
    uniqueEmployers: "नियोक्ता",
    repeatEmployers: "बार-बार बुलाने वाले",
    completionRate: "पूर्ण करने की दर",
    shareWhatsApp: "व्हाट्सएप पर शेयर करें",
    applyNow: "अभी आवेदन करें",
    applied: "आवेदन किया",
    spotsLeft: "जगह बाकी",
    deadline: "अंतिम तिथि",
    budget: "मेहनताना",
    noJobs: "अभी कोई काम नहीं मिला।",
    filterBySkill: "हुनर से छाँटें",
    allSkills: "सभी हुनर",
    searchPlaceholder: "टाइटल या शहर से खोजें...",
    employerProfile: "नियोक्ता",
    trusted: "भरोसेमंद",
    waitingForDecision: "नियोक्ता के जवाब का इंतज़ार...",
    withdraw: "वापस लें",
    goToActive: "चालू काम पर जाएँ",
    confirmed: "स्वीकार",
    rejected: "इस बार नहीं चुने गए",
    noPending: "कोई बकाया आवेदन नहीं।",
    noInvites: "अभी कोई बुलावा नहीं।",
    accept: "स्वीकार करें",
    decline: "मना करें",
    invitedFor: "इस काम के लिए बुलावा",
    activeJobTitle: "आपका मौजूदा काम",
    callEmployer: "नियोक्ता को कॉल करें",
    uploadPhoto: "काम की फ़ोटो डालें",
    takeSelfie: "साइट पर सेल्फी लें",
    markComplete: "काम पूरा हुआ",
    rateEmployer: "नियोक्ता को रेट करें",
    quickTags: "त्वरित टैग",
    reviewText: "और कुछ कहना है? (वैकल्पिक)",
    submit: "भेजें",
    noActiveJob: "अभी कोई चालू काम नहीं।",
    findWork: "काम ढूँढें",
    title: "काम का नाम",
    description: "विवरण",
    address: "पूरा पता",
    workersNeeded: "कारीगरों की संख्या",
    postJobCta: "काम डालें",
    applicants: "आवेदक",
    hire: "रखें",
    pass: "छोड़ें",
    hired: "रखा गया",
    noApplicants: "अभी कोई आवेदक नहीं।",
    browseWorkers: "कारीगर देखें",
    sendInvite: "बुलावा भेजें...",
    completeReview: "पूरा करें और रेट करें",
    noActiveEmp: "कोई चालू काम नहीं।",
    aadhaarVerified: "आधार सत्यापित",
    jobsPosted: "डाले गए काम",
    jobsCompleted: "पूरे किए गए",
    backToList: "वापस",
    languageToggle: "भाषा",
    youAreOffline: "आप नियोक्ताओं से छुपे हैं",
    youAreOnline: "आप नियोक्ताओं को दिख रहे हैं",
    confirmHire: "इस कारीगर को रखें?",
    photoSaved: "फ़ोटो सेव हुई",
    thanks: "धन्यवाद!",
    safeWorkplace: "सुरक्षित जगह",
    fairPayment: "सही भुगतान",
    onTime: "समय पर भुगतान",
    respectful: "सम्मानजनक",
    skilled: "हुनरमंद",
    punctual: "समय का पाबंद",
    polite: "विनम्र",
    neatWork: "साफ काम",
  },
  bn: {
    appName: "রোজগার মিত্র",
    tagline: "বিশ্বস্ত কাজ, সঠিক মজুরি",
    login: "লগ ইন",
    register: "রেজিস্টার",
    username: "ইউজারনেম",
    password: "পাসওয়ার্ড",
    name: "পুরো নাম",
    phone: "ফোন",
    city: "শহর",
    area: "এলাকা",
    skill: "দক্ষতা",
    experience: "অভিজ্ঞতা (বছর)",
    company: "কোম্পানির নাম",
    iAmA: "আমি একজন",
    worker: "শ্রমিক",
    employer: "নিয়োগকর্তা",
    continue: "চালিয়ে যান",
    demoAccounts: "ডেমো অ্যাকাউন্ট (ট্যাপ করে বদলান)",
    search: "কাজ খুঁজুন",
    active: "সক্রিয়",
    pending: "মুলতুবি",
    invites: "আমন্ত্রণ",
    postJob: "কাজ পোস্ট করুন",
    myJobs: "আমার কাজ",
    workers: "শ্রমিকরা",
    activeJobs: "সক্রিয় কাজ",
    profile: "প্রোফাইল",
    history: "কাজের ইতিহাস",
    reviews: "রিভিউ",
    logout: "লগ আউট",
    availability: "আমি কাজের জন্য উপলব্ধ",
    urgentNow: "আমি এখনই উপলব্ধ",
    urgentActive: "🟢 লাইভ — ৮ ঘণ্টার পালস চালু",
    yourPassport: "আপনার কাজের পাসপোর্ট",
    reliabilityScore: "নির্ভরযোগ্যতা স্কোর",
    verifiedJobs: "যাচাইকৃত কাজ",
    avgRating: "গড় রেটিং",
    totalEarned: "মোট আয়",
    uniqueEmployers: "স্বতন্ত্র নিয়োগকর্তা",
    repeatEmployers: "পুনরাবৃত্ত নিয়োগকর্তা",
    completionRate: "সমাপ্তির হার",
    shareWhatsApp: "হোয়াটসঅ্যাপে শেয়ার করুন",
    applyNow: "এখনই আবেদন করুন",
    applied: "আবেদন করা হয়েছে",
    spotsLeft: "স্থান বাকি",
    deadline: "শেষ তারিখ",
    budget: "বাজেট",
    noJobs: "আপনার ফিল্টারের সাথে মেলে এমন কোনো কাজ নেই।",
    filterBySkill: "দক্ষতা দিয়ে ফিল্টার করুন",
    allSkills: "সব দক্ষতা",
    searchPlaceholder: "শিরোনাম বা শহর দিয়ে খুঁজুন...",
    employerProfile: "নিয়োগকর্তা",
    trusted: "বিশ্বস্ত",
    waitingForDecision: "নিয়োগকর্তার জন্য অপেক্ষা...",
    withdraw: "প্রত্যাহার করুন",
    goToActive: "সক্রিয় কাজে যান",
    confirmed: "নিশ্চিত করা হয়েছে",
    rejected: "এবার নির্বাচিত হননি",
    noPending: "কোনো মুলতুবি আবেদন নেই।",
    noInvites: "এখনো কোনো আমন্ত্রণ নেই।",
    accept: "গ্রহণ করুন",
    decline: "প্রত্যাখ্যান করুন",
    invitedFor: "এর জন্য আমন্ত্রিত",
    activeJobTitle: "আপনার বর্তমান কাজ",
    callEmployer: "নিয়োগকর্তাকে কল করুন",
    uploadPhoto: "কাজের ছবি আপলোড করুন",
    takeSelfie: "সাইটে সেলফি তুলুন",
    markComplete: "কাজ সম্পূর্ণ চিহ্নিত করুন",
    rateEmployer: "নিয়োগকর্তাকে রেট করুন",
    quickTags: "দ্রুত ট্যাগ",
    reviewText: "আর কিছু বলার আছে? (ঐচ্ছিক)",
    submit: "জমা দিন",
    noActiveJob: "আপনার এখন কোনো সক্রিয় কাজ নেই।",
    findWork: "কাজ খুঁজুন",
    title: "কাজের শিরোনাম",
    description: "বিবরণ",
    address: "সম্পূর্ণ ঠিকানা",
    workersNeeded: "প্রয়োজনীয় শ্রমিক",
    postJobCta: "কাজ পোস্ট করুন",
    applicants: "আবেদনকারী",
    hire: "নিয়োগ করুন",
    pass: "বাদ দিন",
    hired: "নিয়োগপ্রাপ্ত",
    noApplicants: "এখনো কোনো আবেদনকারী নেই।",
    browseWorkers: "শ্রমিক দেখুন",
    sendInvite: "আমন্ত্রণ পাঠান...",
    completeReview: "সম্পূর্ণ করুন এবং রিভিউ করুন",
    noActiveEmp: "কোনো সক্রিয় কাজ নেই।",
    aadhaarVerified: "আধার যাচাইকৃত",
    jobsPosted: "পোস্ট করা কাজ",
    jobsCompleted: "সম্পন্ন কাজ",
    backToList: "ফিরে যান",
    languageToggle: "ভাষা",
    youAreOffline: "আপনি নিয়োগকর্তাদের থেকে লুকানো আছেন",
    youAreOnline: "আপনি নিয়োগকর্তাদের কাছে দৃশ্যমান",
    confirmHire: "এই শ্রমিককে নিয়োগ করবেন?",
    photoSaved: "ছবি সংরক্ষিত হয়েছে",
    thanks: "ধন্যবাদ!",
    safeWorkplace: "নিরাপদ কর্মক্ষেত্র",
    fairPayment: "ন্যায্য পেমেন্ট",
    onTime: "সময়মতো পরিশোধ করে",
    respectful: "সম্মানজনক",
    skilled: "দক্ষ",
    punctual: "সময়ানুবর্তী",
    polite: "নম্র",
    neatWork: "পরিষ্কার কাজ",
  },
  mr: {
    appName: "रोजगार मित्र",
    tagline: "विश्वासार्ह काम, योग्य मोबदला",
    login: "लॉग इन",
    register: "नोंदणी",
    username: "वापरकर्तानाव",
    password: "पासवर्ड",
    name: "पूर्ण नाव",
    phone: "फोन",
    city: "शहर",
    area: "परिसर",
    skill: "कौशल्य",
    experience: "अनुभव (वर्षे)",
    company: "कंपनीचे नाव",
    iAmA: "मी आहे",
    worker: "कामगार",
    employer: "नियोक्ता",
    continue: "पुढे चला",
    demoAccounts: "डेमो खाती (टॅप करून बदला)",
    search: "काम शोधा",
    active: "सक्रिय",
    pending: "प्रलंबित",
    invites: "आमंत्रणे",
    postJob: "काम पोस्ट करा",
    myJobs: "माझी कामे",
    workers: "कामगार",
    activeJobs: "सक्रिय कामे",
    profile: "प्रोफाइल",
    history: "कामाचा इतिहास",
    reviews: "पुनरावलोकने",
    logout: "बाहेर पडा",
    availability: "मी कामासाठी उपलब्ध आहे",
    urgentNow: "मी आत्ताच उपलब्ध आहे",
    urgentActive: "🟢 लाइव्ह — ८ तासांची पल्स सुरू",
    yourPassport: "तुमचा वर्क पासपोर्ट",
    reliabilityScore: "विश्वासार्हता गुण",
    verifiedJobs: "सत्यापित कामे",
    avgRating: "सरासरी रेटिंग",
    totalEarned: "एकूण कमाई",
    uniqueEmployers: "वेगवेगळे नियोक्ते",
    repeatEmployers: "पुन्हा बोलावणारे नियोक्ते",
    completionRate: "पूर्णत्वाचा दर",
    shareWhatsApp: "व्हॉट्सअॅपवर शेअर करा",
    applyNow: "आता अर्ज करा",
    applied: "अर्ज केला",
    spotsLeft: "जागा शिल्लक",
    deadline: "अंतिम तारीख",
    budget: "मोबदला",
    noJobs: "तुमच्या फिल्टरशी जुळणारे काम अजून नाही.",
    filterBySkill: "कौशल्यानुसार गाळा",
    allSkills: "सर्व कौशल्ये",
    searchPlaceholder: "शीर्षक किंवा शहरानुसार शोधा...",
    employerProfile: "नियोक्ता",
    trusted: "विश्वासार्ह",
    waitingForDecision: "नियोक्त्याच्या उत्तराची वाट पाहत आहे...",
    withdraw: "मागे घ्या",
    goToActive: "सक्रिय कामाकडे जा",
    confirmed: "पुष्टी झाली",
    rejected: "यावेळी निवड झाली नाही",
    noPending: "कोणतेही प्रलंबित अर्ज नाहीत.",
    noInvites: "अजून कोणतेही आमंत्रण नाही.",
    accept: "स्वीकार करा",
    decline: "नकार द्या",
    invitedFor: "यासाठी आमंत्रित",
    activeJobTitle: "तुमचे सध्याचे काम",
    callEmployer: "नियोक्त्याला कॉल करा",
    uploadPhoto: "कामाचा फोटो अपलोड करा",
    takeSelfie: "साइटवर सेल्फी घ्या",
    markComplete: "काम पूर्ण म्हणून चिन्हांकित करा",
    rateEmployer: "नियोक्त्याला रेट करा",
    quickTags: "त्वरित टॅग",
    reviewText: "आणखी काही सांगायचे आहे का? (पर्यायी)",
    submit: "सबमिट करा",
    noActiveJob: "तुमच्याकडे सध्या कोणतेही सक्रिय काम नाही.",
    findWork: "काम शोधा",
    title: "कामाचे शीर्षक",
    description: "वर्णन",
    address: "संपूर्ण पत्ता",
    workersNeeded: "आवश्यक कामगार",
    postJobCta: "काम पोस्ट करा",
    applicants: "अर्जदार",
    hire: "कामावर ठेवा",
    pass: "सोडा",
    hired: "कामावर घेतले",
    noApplicants: "अजून कोणीही अर्जदार नाही.",
    browseWorkers: "कामगार पहा",
    sendInvite: "आमंत्रण पाठवा...",
    completeReview: "पूर्ण करा आणि पुनरावलोकन करा",
    noActiveEmp: "कोणतेही सक्रिय काम नाही.",
    aadhaarVerified: "आधार सत्यापित",
    jobsPosted: "पोस्ट केलेली कामे",
    jobsCompleted: "पूर्ण झालेली कामे",
    backToList: "मागे",
    languageToggle: "भाषा",
    youAreOffline: "तुम्ही नियोक्त्यांपासून लपलेले आहात",
    youAreOnline: "तुम्ही नियोक्त्यांना दिसत आहात",
    confirmHire: "या कामगाराला कामावर ठेवायचे?",
    photoSaved: "फोटो जतन झाला",
    thanks: "धन्यवाद!",
    safeWorkplace: "सुरक्षित कामाची जागा",
    fairPayment: "योग्य पेमेंट",
    onTime: "वेळेवर पैसे देतो",
    respectful: "आदरयुक्त",
    skilled: "कुशल",
    punctual: "वक्तशीर",
    polite: "विनम्र",
    neatWork: "नीटनेटके काम",
  },
  te: {
    appName: "రోజ్‌గార్ మిత్ర",
    tagline: "నమ్మకమైన పని, న్యాయమైన వేతనం",
    login: "లాగిన్",
    register: "నమోదు",
    username: "వినియోగదారు పేరు",
    password: "పాస్‌వర్డ్",
    name: "పూర్తి పేరు",
    phone: "ఫోన్",
    city: "నగరం",
    area: "ప్రాంతం",
    skill: "నైపుణ్యం",
    experience: "అనుభవం (సంవత్సరాలు)",
    company: "కంపెనీ పేరు",
    iAmA: "నేను ఒక",
    worker: "పనివాడు",
    employer: "యజమాని",
    continue: "కొనసాగించు",
    demoAccounts: "డెమో ఖాతాలు (మార్చడానికి నొక్కండి)",
    search: "పనులు వెతకండి",
    active: "యాక్టివ్",
    pending: "పెండింగ్",
    invites: "ఆహ్వానాలు",
    postJob: "పని పోస్ట్ చేయండి",
    myJobs: "నా పనులు",
    workers: "పనివారు",
    activeJobs: "యాక్టివ్ పనులు",
    profile: "ప్రొఫైల్",
    history: "పని చరిత్ర",
    reviews: "రివ్యూలు",
    logout: "లాగ్ అవుట్",
    availability: "నేను పనికి అందుబాటులో ఉన్నాను",
    urgentNow: "నేను ఇప్పుడే అందుబాటులో ఉన్నాను",
    urgentActive: "🟢 లైవ్ — 8 గంటల పల్స్ యాక్టివ్",
    yourPassport: "మీ వర్క్ పాస్‌పోర్ట్",
    reliabilityScore: "విశ్వసనీయత స్కోరు",
    verifiedJobs: "ధృవీకరించిన పనులు",
    avgRating: "సగటు రేటింగ్",
    totalEarned: "మొత్తం సంపాదన",
    uniqueEmployers: "విభిన్న యజమానులు",
    repeatEmployers: "మళ్ళీ మళ్ళీ పిలిచే యజమానులు",
    completionRate: "పూర్తి రేటు",
    shareWhatsApp: "వాట్సాప్‌లో షేర్ చేయండి",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    applied: "దరఖాస్తు చేశారు",
    spotsLeft: "స్థానాలు మిగిలి ఉన్నాయి",
    deadline: "గడువు తేదీ",
    budget: "బడ్జెట్",
    noJobs: "మీ ఫిల్టర్‌లకు సరిపోయే పనులు లేవు.",
    filterBySkill: "నైపుణ్యం ద్వారా ఫిల్టర్ చేయండి",
    allSkills: "అన్ని నైపుణ్యాలు",
    searchPlaceholder: "శీర్షిక లేదా నగరం ద్వారా వెతకండి...",
    employerProfile: "యజమాని",
    trusted: "నమ్మదగిన",
    waitingForDecision: "యజమాని కోసం ఎదురుచూస్తున్నారు...",
    withdraw: "ఉపసంహరించుకోండి",
    goToActive: "యాక్టివ్ పనికి వెళ్ళండి",
    confirmed: "ధృవీకరించబడింది",
    rejected: "ఈసారి ఎంపిక కాలేదు",
    noPending: "పెండింగ్ దరఖాస్తులు లేవు.",
    noInvites: "ఇంకా ఆహ్వానాలు లేవు.",
    accept: "అంగీకరించండి",
    decline: "తిరస్కరించండి",
    invitedFor: "దీని కోసం ఆహ్వానించారు",
    activeJobTitle: "మీ ప్రస్తుత పని",
    callEmployer: "యజమానికి కాల్ చేయండి",
    uploadPhoto: "పని ఫోటో అప్‌లోడ్ చేయండి",
    takeSelfie: "సైట్‌లో సెల్ఫీ తీయండి",
    markComplete: "పని పూర్తైనట్లు గుర్తించండి",
    rateEmployer: "యజమానికి రేటింగ్ ఇవ్వండి",
    quickTags: "త్వరిత ట్యాగ్‌లు",
    reviewText: "ఇంకేమైనా చెప్పాలా? (ఐచ్ఛికం)",
    submit: "సమర్పించండి",
    noActiveJob: "మీకు ప్రస్తుతం యాక్టివ్ పని లేదు.",
    findWork: "పని వెతకండి",
    title: "ఉద్యోగ శీర్షిక",
    description: "వివరణ",
    address: "పూర్తి చిరునామా",
    workersNeeded: "అవసరమైన పనివారు",
    postJobCta: "ఉద్యోగం పోస్ట్ చేయండి",
    applicants: "దరఖాస్తుదారులు",
    hire: "నియమించండి",
    pass: "వదిలివేయండి",
    hired: "నియమించారు",
    noApplicants: "ఇంకా దరఖాస్తుదారులు లేరు.",
    browseWorkers: "పనివారిని చూడండి",
    sendInvite: "ఆహ్వానం పంపండి...",
    completeReview: "పూర్తి చేసి రివ్యూ చేయండి",
    noActiveEmp: "యాక్టివ్ పనులు లేవు.",
    aadhaarVerified: "ఆధార్ ధృవీకరించబడింది",
    jobsPosted: "పోస్ట్ చేసిన పనులు",
    jobsCompleted: "పూర్తయిన పనులు",
    backToList: "వెనుకకు",
    languageToggle: "భాష",
    youAreOffline: "మీరు యజమానుల నుండి దాచబడ్డారు",
    youAreOnline: "మీరు యజమానులకు కనిపిస్తున్నారు",
    confirmHire: "ఈ పనివారిని నియమిస్తారా?",
    photoSaved: "ఫోటో సేవ్ అయింది",
    thanks: "ధన్యవాదాలు!",
    safeWorkplace: "సురక్షితమైన పని స్థలం",
    fairPayment: "న్యాయమైన చెల్లింపు",
    onTime: "సమయానికి చెల్లిస్తారు",
    respectful: "గౌరవప్రదమైన",
    skilled: "నైపుణ్యం కలిగిన",
    punctual: "సమయపాలన కలిగిన",
    polite: "మర్యాదపూర్వకమైన",
    neatWork: "శుభ్రమైన పని",
  },
  ta: {
    appName: "ரோஜ்கார் மித்ரா",
    tagline: "நம்பகமான வேலை, நியாயமான ஊதியம்",
    login: "உள்நுழை",
    register: "பதிவு செய்",
    username: "பயனர்பெயர்",
    password: "கடவுச்சொல்",
    name: "முழு பெயர்",
    phone: "தொலைபேசி",
    city: "நகரம்",
    area: "பகுதி",
    skill: "திறமை",
    experience: "அனுபவம் (ஆண்டுகள்)",
    company: "நிறுவனத்தின் பெயர்",
    iAmA: "நான் ஒரு",
    worker: "தொழிலாளி",
    employer: "முதலாளி",
    continue: "தொடரவும்",
    demoAccounts: "டெமோ கணக்குகள் (மாற்ற தட்டவும்)",
    search: "வேலைகளைத் தேடு",
    active: "செயலில்",
    pending: "நிலுவையில்",
    invites: "அழைப்புகள்",
    postJob: "வேலை இடுங்கள்",
    myJobs: "என் வேலைகள்",
    workers: "தொழிலாளர்கள்",
    activeJobs: "செயலில் உள்ள வேலைகள்",
    profile: "சுயவிவரம்",
    history: "வேலை வரலாறு",
    reviews: "மதிப்புரைகள்",
    logout: "வெளியேறு",
    availability: "நான் வேலைக்குக் கிடைக்கிறேன்",
    urgentNow: "நான் இப்போதே கிடைக்கிறேன்",
    urgentActive: "🟢 நேரலை — 8 மணி நேர பல்ஸ் இயங்குகிறது",
    yourPassport: "உங்கள் பணி பாஸ்போர்ட்",
    reliabilityScore: "நம்பகத்தன்மை மதிப்பெண்",
    verifiedJobs: "சரிபார்க்கப்பட்ட வேலைகள்",
    avgRating: "சராசரி மதிப்பீடு",
    totalEarned: "மொத்த வருமானம்",
    uniqueEmployers: "தனித்துவ முதலாளிகள்",
    repeatEmployers: "மீண்டும் அழைக்கும் முதலாளிகள்",
    completionRate: "நிறைவு விகிதம்",
    shareWhatsApp: "வாட்ஸ்அப்பில் பகிரவும்",
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    applied: "விண்ணப்பித்தது",
    spotsLeft: "இடங்கள் மீதம்",
    deadline: "கடைசி தேதி",
    budget: "பட்ஜெட்",
    noJobs: "உங்கள் வடிகட்டிக்கு பொருந்தும் வேலைகள் இல்லை.",
    filterBySkill: "திறமையால் வடிகட்டு",
    allSkills: "அனைத்து திறமைகள்",
    searchPlaceholder: "தலைப்பு அல்லது நகரம் மூலம் தேடு...",
    employerProfile: "முதலாளி",
    trusted: "நம்பகமான",
    waitingForDecision: "முதலாளிக்காக காத்திருக்கிறது...",
    withdraw: "திரும்பப் பெறு",
    goToActive: "செயலில் உள்ள வேலைக்குச் செல்லவும்",
    confirmed: "உறுதிசெய்யப்பட்டது",
    rejected: "இந்த முறை தேர்ந்தெடுக்கப்படவில்லை",
    noPending: "நிலுவையில் விண்ணப்பங்கள் இல்லை.",
    noInvites: "இன்னும் அழைப்புகள் இல்லை.",
    accept: "ஏற்றுக்கொள்",
    decline: "மறு",
    invitedFor: "இதற்காக அழைக்கப்பட்டது",
    activeJobTitle: "உங்கள் தற்போதைய வேலை",
    callEmployer: "முதலாளியை அழைக்கவும்",
    uploadPhoto: "வேலைப் புகைப்படத்தை பதிவேற்றவும்",
    takeSelfie: "தளத்தில் செல்பி எடுக்கவும்",
    markComplete: "வேலையை முடிந்ததாகக் குறிக்கவும்",
    rateEmployer: "முதலாளியை மதிப்பிடுங்கள்",
    quickTags: "விரைவு குறிச்சொற்கள்",
    reviewText: "வேறு ஏதேனும் சொல்ல வேண்டுமா? (விருப்பம்)",
    submit: "சமர்ப்பி",
    noActiveJob: "உங்களுக்கு தற்போது செயலில் வேலை இல்லை.",
    findWork: "வேலை தேடு",
    title: "வேலை தலைப்பு",
    description: "விவரம்",
    address: "முழு முகவரி",
    workersNeeded: "தேவையான தொழிலாளர்கள்",
    postJobCta: "வேலையை இடுங்கள்",
    applicants: "விண்ணப்பதாரர்கள்",
    hire: "வேலைக்கு அமர்த்து",
    pass: "தவிர்",
    hired: "வேலைக்கு அமர்த்தப்பட்டது",
    noApplicants: "இன்னும் விண்ணப்பதாரர்கள் இல்லை.",
    browseWorkers: "தொழிலாளர்களைப் பார்க்கவும்",
    sendInvite: "அழைப்பை அனுப்பவும்...",
    completeReview: "முடித்து மதிப்பாய்வு செய்",
    noActiveEmp: "செயலில் வேலைகள் இல்லை.",
    aadhaarVerified: "ஆதார் சரிபார்க்கப்பட்டது",
    jobsPosted: "இடப்பட்ட வேலைகள்",
    jobsCompleted: "முடிக்கப்பட்ட வேலைகள்",
    backToList: "பின்செல்",
    languageToggle: "மொழி",
    youAreOffline: "நீங்கள் முதலாளிகளிடமிருந்து மறைந்துள்ளீர்கள்",
    youAreOnline: "நீங்கள் முதலாளிகளுக்குத் தெரிகிறீர்கள்",
    confirmHire: "இந்த தொழிலாளியை வேலைக்கு அமர்த்தவா?",
    photoSaved: "புகைப்படம் சேமிக்கப்பட்டது",
    thanks: "நன்றி!",
    safeWorkplace: "பாதுகாப்பான பணியிடம்",
    fairPayment: "நியாயமான கட்டணம்",
    onTime: "சரியான நேரத்தில் பணம் தருகிறார்",
    respectful: "மரியாதைக்குரிய",
    skilled: "திறமையான",
    punctual: "நேரம் தவறாதவர்",
    polite: "பணிவான",
    neatWork: "நேர்த்தியான வேலை",
  },
  gu: {
    appName: "રોજગાર મિત્ર",
    tagline: "વિશ્વસનીય કામ, વાજબી વેતન",
    login: "લોગિન",
    register: "રજિસ્ટર",
    username: "યુઝરનેમ",
    password: "પાસવર્ડ",
    name: "પૂરું નામ",
    phone: "ફોન",
    city: "શહેર",
    area: "વિસ્તાર",
    skill: "કૌશલ્ય",
    experience: "અનુભવ (વર્ષ)",
    company: "કંપનીનું નામ",
    iAmA: "હું છું",
    worker: "કારીગર",
    employer: "નોકરીદાતા",
    continue: "ચાલુ રાખો",
    demoAccounts: "ડેમો ખાતાં (બદલવા ટેપ કરો)",
    search: "કામ શોધો",
    active: "સક્રિય",
    pending: "બાકી",
    invites: "આમંત્રણો",
    postJob: "કામ પોસ્ટ કરો",
    myJobs: "મારાં કામ",
    workers: "કારીગરો",
    activeJobs: "સક્રિય કામો",
    profile: "પ્રોફાઇલ",
    history: "કામનો ઇતિહાસ",
    reviews: "સમીક્ષાઓ",
    logout: "લોગઆઉટ",
    availability: "હું કામ માટે ઉપલબ્ધ છું",
    urgentNow: "હું અત્યારે જ ઉપલબ્ધ છું",
    urgentActive: "🟢 લાઇવ — 8 કલાકનું પલ્સ ચાલુ",
    yourPassport: "તમારો વર્ક પાસપોર્ટ",
    reliabilityScore: "વિશ્વસનીયતા સ્કોર",
    verifiedJobs: "ચકાસાયેલા કામો",
    avgRating: "સરેરાશ રેટિંગ",
    totalEarned: "કુલ કમાણી",
    uniqueEmployers: "અલગ નોકરીદાતાઓ",
    repeatEmployers: "ફરી બોલાવતા નોકરીદાતાઓ",
    completionRate: "પૂર્ણતા દર",
    shareWhatsApp: "વોટ્સએપ પર શેર કરો",
    applyNow: "હમણાં અરજી કરો",
    applied: "અરજી કરી",
    spotsLeft: "જગ્યા બાકી",
    deadline: "છેલ્લી તારીખ",
    budget: "બજેટ",
    noJobs: "તમારા ફિલ્ટર સાથે મેળ ખાતું કોઈ કામ નથી.",
    filterBySkill: "કૌશલ્ય પ્રમાણે ફિલ્ટર કરો",
    allSkills: "બધા કૌશલ્યો",
    searchPlaceholder: "શીર્ષક કે શહેર દ્વારા શોધો...",
    employerProfile: "નોકરીદાતા",
    trusted: "વિશ્વસનીય",
    waitingForDecision: "નોકરીદાતાની રાહ જોવાઈ રહી છે...",
    withdraw: "પાછું ખેંચો",
    goToActive: "સક્રિય કામ પર જાઓ",
    confirmed: "પુષ્ટિ થઈ",
    rejected: "આ વખતે પસંદ થયા નથી",
    noPending: "કોઈ બાકી અરજી નથી.",
    noInvites: "હજુ કોઈ આમંત્રણ નથી.",
    accept: "સ્વીકારો",
    decline: "નકારો",
    invitedFor: "આ માટે આમંત્રિત",
    activeJobTitle: "તમારું વર્તમાન કામ",
    callEmployer: "નોકરીદાતાને કૉલ કરો",
    uploadPhoto: "કામનો ફોટો અપલોડ કરો",
    takeSelfie: "સાઇટ પર સેલ્ફી લો",
    markComplete: "કામ પૂર્ણ તરીકે ચિહ્નિત કરો",
    rateEmployer: "નોકરીદાતાને રેટ કરો",
    quickTags: "ઝડપી ટૅગ્સ",
    reviewText: "બીજું કંઈ કહેવું છે? (વૈકલ્પિક)",
    submit: "સબમિટ કરો",
    noActiveJob: "તમારી પાસે અત્યારે કોઈ સક્રિય કામ નથી.",
    findWork: "કામ શોધો",
    title: "કામનું શીર્ષક",
    description: "વર્ણન",
    address: "સંપૂર્ણ સરનામું",
    workersNeeded: "જરૂરી કારીગરો",
    postJobCta: "કામ પોસ્ટ કરો",
    applicants: "અરજદારો",
    hire: "નોકરી પર રાખો",
    pass: "છોડો",
    hired: "નોકરી પર રખાયું",
    noApplicants: "હજુ કોઈ અરજદાર નથી.",
    browseWorkers: "કારીગરો જુઓ",
    sendInvite: "આમંત્રણ મોકલો...",
    completeReview: "પૂર્ણ કરો અને સમીક્ષા કરો",
    noActiveEmp: "કોઈ સક્રિય કામ નથી.",
    aadhaarVerified: "આધાર ચકાસાયેલ",
    jobsPosted: "પોસ્ટ કરેલા કામો",
    jobsCompleted: "પૂર્ણ થયેલા કામો",
    backToList: "પાછળ",
    languageToggle: "ભાષા",
    youAreOffline: "તમે નોકરીદાતાઓથી છુપાયેલા છો",
    youAreOnline: "તમે નોકરીદાતાઓને દેખાઈ રહ્યા છો",
    confirmHire: "આ કારીગરને નોકરી પર રાખવા?",
    photoSaved: "ફોટો સેવ થયો",
    thanks: "આભાર!",
    safeWorkplace: "સુરક્ષિત કાર્યસ્થળ",
    fairPayment: "વાજબી ચુકવણી",
    onTime: "સમયસર ચૂકવણી કરે છે",
    respectful: "આદરપૂર્ણ",
    skilled: "કુશળ",
    punctual: "સમયના પાબંદ",
    polite: "નમ્ર",
    neatWork: "ચોખ્ખું કામ",
  },
  ur: {
    appName: "روزگار مِتر",
    tagline: "بھروسے مند کام، مناسب اجرت",
    login: "لاگ ان",
    register: "رجسٹر",
    username: "یوزر نیم",
    password: "پاس ورڈ",
    name: "پورا نام",
    phone: "فون",
    city: "شہر",
    area: "علاقہ",
    skill: "ہنر",
    experience: "تجربہ (سال)",
    company: "کمپنی کا نام",
    iAmA: "میں ہوں",
    worker: "مزدور",
    employer: "آجر",
    continue: "جاری رکھیں",
    demoAccounts: "ڈیمو اکاؤنٹس (تبدیل کرنے کے لیے ٹیپ کریں)",
    search: "کام تلاش کریں",
    active: "فعال",
    pending: "زیر التواء",
    invites: "دعوت نامے",
    postJob: "کام پوسٹ کریں",
    myJobs: "میرے کام",
    workers: "مزدور",
    activeJobs: "فعال کام",
    profile: "پروفائل",
    history: "کام کی تاریخ",
    reviews: "جائزے",
    logout: "لاگ آؤٹ",
    availability: "میں کام کے لیے دستیاب ہوں",
    urgentNow: "میں ابھی دستیاب ہوں",
    urgentActive: "🟢 لائیو — 8 گھنٹے کی پلس فعال",
    yourPassport: "آپ کا ورک پاسپورٹ",
    reliabilityScore: "اعتماد کا اسکور",
    verifiedJobs: "تصدیق شدہ کام",
    avgRating: "اوسط ریٹنگ",
    totalEarned: "کل کمائی",
    uniqueEmployers: "مختلف آجر",
    repeatEmployers: "بار بار بلانے والے آجر",
    completionRate: "تکمیل کی شرح",
    shareWhatsApp: "واٹس ایپ پر شیئر کریں",
    applyNow: "ابھی درخواست دیں",
    applied: "درخواست دی گئی",
    spotsLeft: "جگہ باقی",
    deadline: "آخری تاریخ",
    budget: "بجٹ",
    noJobs: "آپ کے فلٹرز سے میل کھاتا کوئی کام نہیں۔",
    filterBySkill: "ہنر کے حساب سے فلٹر کریں",
    allSkills: "تمام ہنر",
    searchPlaceholder: "عنوان یا شہر سے تلاش کریں...",
    employerProfile: "آجر",
    trusted: "قابل اعتماد",
    waitingForDecision: "آجر کا انتظار ہے...",
    withdraw: "واپس لیں",
    goToActive: "فعال کام پر جائیں",
    confirmed: "تصدیق شدہ",
    rejected: "اس بار منتخب نہیں ہوئے",
    noPending: "کوئی زیر التواء درخواست نہیں۔",
    noInvites: "ابھی تک کوئی دعوت نامہ نہیں۔",
    accept: "قبول کریں",
    decline: "مسترد کریں",
    invitedFor: "اس کے لیے مدعو کیا گیا",
    activeJobTitle: "آپ کا موجودہ کام",
    callEmployer: "آجر کو کال کریں",
    uploadPhoto: "کام کی تصویر اپ لوڈ کریں",
    takeSelfie: "سائٹ پر سیلفی لیں",
    markComplete: "کام مکمل نشان زد کریں",
    rateEmployer: "آجر کو ریٹ کریں",
    quickTags: "فوری ٹیگز",
    reviewText: "کچھ اور کہنا ہے؟ (اختیاری)",
    submit: "جمع کریں",
    noActiveJob: "آپ کے پاس ابھی کوئی فعال کام نہیں ہے۔",
    findWork: "کام تلاش کریں",
    title: "کام کا عنوان",
    description: "تفصیل",
    address: "مکمل پتہ",
    workersNeeded: "درکار مزدور",
    postJobCta: "کام پوسٹ کریں",
    applicants: "درخواست دہندگان",
    hire: "ملازم رکھیں",
    pass: "چھوڑیں",
    hired: "ملازم رکھا گیا",
    noApplicants: "ابھی تک کوئی درخواست دہندہ نہیں۔",
    browseWorkers: "مزدور دیکھیں",
    sendInvite: "دعوت بھیجیں...",
    completeReview: "مکمل کریں اور جائزہ لیں",
    noActiveEmp: "کوئی فعال کام نہیں۔",
    aadhaarVerified: "آدھار تصدیق شدہ",
    jobsPosted: "پوسٹ کیے گئے کام",
    jobsCompleted: "مکمل کیے گئے کام",
    backToList: "واپس",
    languageToggle: "زبان",
    youAreOffline: "آپ آجروں سے چھپے ہوئے ہیں",
    youAreOnline: "آپ آجروں کو نظر آ رہے ہیں",
    confirmHire: "اس مزدور کو ملازم رکھیں؟",
    photoSaved: "تصویر محفوظ ہو گئی",
    thanks: "شکریہ!",
    safeWorkplace: "محفوظ کام کی جگہ",
    fairPayment: "مناسب ادائیگی",
    onTime: "وقت پر ادائیگی کرتا ہے",
    respectful: "باعزت",
    skilled: "ماہر",
    punctual: "وقت کا پابند",
    polite: "شائستہ",
    neatWork: "صاف ستھرا کام",
  },
  kn: {
    appName: "ರೋಜ್ಗಾರ್ ಮಿತ್ರ",
    tagline: "ವಿಶ್ವಾಸಾರ್ಹ ಕೆಲಸ, ನ್ಯಾಯಯುತ ಸಂಬಳ",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    username: "ಬಳಕೆದಾರ ಹೆಸರು",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಫೋನ್",
    city: "ನಗರ",
    area: "ಪ್ರದೇಶ",
    skill: "ಕೌಶಲ್ಯ",
    experience: "ಅನುಭವ (ವರ್ಷಗಳು)",
    company: "ಕಂಪನಿ ಹೆಸರು",
    iAmA: "ನಾನು ಒಬ್ಬ",
    worker: "ಕಾರ್ಮಿಕ",
    employer: "ಉದ್ಯೋಗದಾತ",
    continue: "ಮುಂದುವರಿಸಿ",
    demoAccounts: "ಡೆಮೊ ಖಾತೆಗಳು (ಬದಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ)",
    search: "ಕೆಲಸ ಹುಡುಕಿ",
    active: "ಸಕ್ರಿಯ",
    pending: "ಬಾಕಿ",
    invites: "ಆಹ್ವಾನಗಳು",
    postJob: "ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ",
    myJobs: "ನನ್ನ ಕೆಲಸಗಳು",
    workers: "ಕಾರ್ಮಿಕರು",
    activeJobs: "ಸಕ್ರಿಯ ಕೆಲಸಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    history: "ಕೆಲಸದ ಇತಿಹಾಸ",
    reviews: "ವಿಮರ್ಶೆಗಳು",
    logout: "ಲಾಗ್ಔಟ್",
    availability: "ನಾನು ಕೆಲಸಕ್ಕೆ ಲಭ್ಯವಿದ್ದೇನೆ",
    urgentNow: "ನಾನು ಈಗಲೇ ಲಭ್ಯವಿದ್ದೇನೆ",
    urgentActive: "🟢 ಲೈವ್ — 8 ಗಂಟೆಗಳ ಪಲ್ಸ್ ಸಕ್ರಿಯ",
    yourPassport: "ನಿಮ್ಮ ಕೆಲಸದ ಪಾಸ್‌ಪೋರ್ಟ್",
    reliabilityScore: "ವಿಶ್ವಾಸಾರ್ಹತಾ ಅಂಕ",
    verifiedJobs: "ಪರಿಶೀಲಿಸಿದ ಕೆಲಸಗಳು",
    avgRating: "ಸರಾಸರಿ ರೇಟಿಂಗ್",
    totalEarned: "ಒಟ್ಟು ಗಳಿಕೆ",
    uniqueEmployers: "ವಿಭಿನ್ನ ಉದ್ಯೋಗದಾತರು",
    repeatEmployers: "ಮತ್ತೆ ಮತ್ತೆ ಕರೆಯುವ ಉದ್ಯೋಗದಾತರು",
    completionRate: "ಪೂರ್ಣಗೊಂಡ ದರ",
    shareWhatsApp: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ",
    applyNow: "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    applied: "ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    spotsLeft: "ಸ್ಥಳಗಳು ಬಾಕಿ",
    deadline: "ಕೊನೆಯ ದಿನಾಂಕ",
    budget: "ಬಜೆಟ್",
    noJobs: "ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗೆ ಹೊಂದುವ ಕೆಲಸ ಇಲ್ಲ.",
    filterBySkill: "ಕೌಶಲ್ಯದ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    allSkills: "ಎಲ್ಲಾ ಕೌಶಲ್ಯಗಳು",
    searchPlaceholder: "ಶೀರ್ಷಿಕೆ ಅಥವಾ ನಗರದಿಂದ ಹುಡುಕಿ...",
    employerProfile: "ಉದ್ಯೋಗದಾತ",
    trusted: "ವಿಶ್ವಾಸಾರ್ಹ",
    waitingForDecision: "ಉದ್ಯೋಗದಾತರಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ...",
    withdraw: "ಹಿಂಪಡೆಯಿರಿ",
    goToActive: "ಸಕ್ರಿಯ ಕೆಲಸಕ್ಕೆ ಹೋಗಿ",
    confirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    rejected: "ಈ ಬಾರಿ ಆಯ್ಕೆಯಾಗಿಲ್ಲ",
    noPending: "ಬಾಕಿ ಅರ್ಜಿಗಳಿಲ್ಲ.",
    noInvites: "ಇನ್ನೂ ಆಹ್ವಾನಗಳಿಲ್ಲ.",
    accept: "ಸ್ವೀಕರಿಸಿ",
    decline: "ನಿರಾಕರಿಸಿ",
    invitedFor: "ಇದಕ್ಕಾಗಿ ಆಹ್ವಾನಿಸಲಾಗಿದೆ",
    activeJobTitle: "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಕೆಲಸ",
    callEmployer: "ಉದ್ಯೋಗದಾತರಿಗೆ ಕರೆ ಮಾಡಿ",
    uploadPhoto: "ಕೆಲಸದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    takeSelfie: "ಸೈಟ್‌ನಲ್ಲಿ ಸೆಲ್ಫಿ ತೆಗೆಯಿರಿ",
    markComplete: "ಕೆಲಸ ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    rateEmployer: "ಉದ್ಯೋಗದಾತರಿಗೆ ರೇಟ್ ಮಾಡಿ",
    quickTags: "ತ್ವರಿತ ಟ್ಯಾಗ್‌ಗಳು",
    reviewText: "ಇನ್ನೇನಾದರೂ ಹೇಳಬೇಕೆ? (ಐಚ್ಛಿಕ)",
    submit: "ಸಲ್ಲಿಸಿ",
    noActiveJob: "ನಿಮಗೆ ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೆಲಸ ಇಲ್ಲ.",
    findWork: "ಕೆಲಸ ಹುಡುಕಿ",
    title: "ಕೆಲಸದ ಶೀರ್ಷಿಕೆ",
    description: "ವಿವರಣೆ",
    address: "ಪೂರ್ಣ ವಿಳಾಸ",
    workersNeeded: "ಅಗತ್ಯವಿರುವ ಕಾರ್ಮಿಕರು",
    postJobCta: "ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ",
    applicants: "ಅರ್ಜಿದಾರರು",
    hire: "ನೇಮಿಸಿ",
    pass: "ಬಿಡಿ",
    hired: "ನೇಮಿಸಲಾಗಿದೆ",
    noApplicants: "ಇನ್ನೂ ಅರ್ಜಿದಾರರಿಲ್ಲ.",
    browseWorkers: "ಕಾರ್ಮಿಕರನ್ನು ವೀಕ್ಷಿಸಿ",
    sendInvite: "ಆಹ್ವಾನ ಕಳುಹಿಸಿ...",
    completeReview: "ಪೂರ್ಣಗೊಳಿಸಿ ಮತ್ತು ವಿಮರ್ಶಿಸಿ",
    noActiveEmp: "ಸಕ್ರಿಯ ಕೆಲಸಗಳಿಲ್ಲ.",
    aadhaarVerified: "ಆಧಾರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    jobsPosted: "ಪೋಸ್ಟ್ ಮಾಡಿದ ಕೆಲಸಗಳು",
    jobsCompleted: "ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು",
    backToList: "ಹಿಂದೆ",
    languageToggle: "ಭಾಷೆ",
    youAreOffline: "ನೀವು ಉದ್ಯೋಗದಾತರಿಂದ ಅಡಗಿದ್ದೀರಿ",
    youAreOnline: "ನೀವು ಉದ್ಯೋಗದಾತರಿಗೆ ಗೋಚರಿಸುತ್ತೀರಿ",
    confirmHire: "ಈ ಕಾರ್ಮಿಕರನ್ನು ನೇಮಿಸುವುದೇ?",
    photoSaved: "ಫೋಟೋ ಉಳಿಸಲಾಗಿದೆ",
    thanks: "ಧನ್ಯವಾದಗಳು!",
    safeWorkplace: "ಸುರಕ್ಷಿತ ಕೆಲಸದ ಸ್ಥಳ",
    fairPayment: "ನ್ಯಾಯಯುತ ಪಾವತಿ",
    onTime: "ಸಮಯಕ್ಕೆ ಪಾವತಿಸುತ್ತಾರೆ",
    respectful: "ಗೌರವಯುತ",
    skilled: "ಕುಶಲ",
    punctual: "ಸಮಯಪಾಲಕ",
    polite: "ವಿನಯಶೀಲ",
    neatWork: "ಅಚ್ಚುಕಟ್ಟಾದ ಕೆಲಸ",
  },
  or: {
    appName: "ରୋଜଗାର ମିତ୍ର",
    tagline: "ବିଶ୍ୱାସଯୋଗ୍ୟ କାମ, ନ୍ୟାୟ୍ୟ ମଜୁରି",
    login: "ଲଗଇନ",
    register: "ପଞ୍ଜୀକରଣ",
    username: "ୟୁଜରନେମ",
    password: "ପାସୱାର୍ଡ",
    name: "ପୂର୍ଣ୍ଣ ନାମ",
    phone: "ଫୋନ",
    city: "ସହର",
    area: "ଅଞ୍ଚଳ",
    skill: "କୌଶଳ",
    experience: "ଅଭିଜ୍ଞତା (ବର୍ଷ)",
    company: "କମ୍ପାନୀ ନାମ",
    iAmA: "ମୁଁ ଜଣେ",
    worker: "ଶ୍ରମିକ",
    employer: "ନିଯୁକ୍ତିଦାତା",
    continue: "ଆଗକୁ ବଢ଼ନ୍ତୁ",
    demoAccounts: "ଡେମୋ ଆକାଉଣ୍ଟ (ବଦଳାଇବାକୁ ଟାପ୍ କରନ୍ତୁ)",
    search: "କାମ ଖୋଜନ୍ତୁ",
    active: "ସକ୍ରିୟ",
    pending: "ବକେୟା",
    invites: "ନିମନ୍ତ୍ରଣ",
    postJob: "କାମ ପୋଷ୍ଟ କରନ୍ତୁ",
    myJobs: "ମୋ କାମ",
    workers: "ଶ୍ରମିକମାନେ",
    activeJobs: "ସକ୍ରିୟ କାମ",
    profile: "ପ୍ରୋଫାଇଲ",
    history: "କାମର ଇତିହାସ",
    reviews: "ସମୀକ୍ଷା",
    logout: "ଲଗଆଉଟ",
    availability: "ମୁଁ କାମ ପାଇଁ ଉପଲବ୍ଧ",
    urgentNow: "ମୁଁ ବର୍ତ୍ତମାନ ଉପଲବ୍ଧ",
    urgentActive: "🟢 ଲାଇଭ — 8 ଘଣ୍ଟା ପଲ୍ସ ସକ୍ରିୟ",
    yourPassport: "ଆପଣଙ୍କ କାର୍ଯ୍ୟ ପାସପୋର୍ଟ",
    reliabilityScore: "ବିଶ୍ୱାସନୀୟତା ସ୍କୋର",
    verifiedJobs: "ଯାଞ୍ଚ ହୋଇଥିବା କାମ",
    avgRating: "ହାରାହାରି ରେଟିଂ",
    totalEarned: "ମୋଟ ରୋଜଗାର",
    uniqueEmployers: "ଭିନ୍ନ ନିଯୁକ୍ତିଦାତା",
    repeatEmployers: "ପୁନଃ ପୁନଃ ଡକାଉଥିବା ନିଯୁକ୍ତିଦାତା",
    completionRate: "ସମାପ୍ତି ହାର",
    shareWhatsApp: "ହ୍ୱାଟସଆପରେ ସେୟାର କରନ୍ତୁ",
    applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
    applied: "ଆବେଦନ କରାଯାଇଛି",
    spotsLeft: "ସ୍ଥାନ ବାକି",
    deadline: "ଶେଷ ତାରିଖ",
    budget: "ବଜେଟ",
    noJobs: "ଆପଣଙ୍କ ଫିଲ୍ଟର ସହିତ ମେଳ ଖାଉଥିବା କାମ ନାହିଁ।",
    filterBySkill: "କୌଶଳ ଅନୁସାରେ ଫିଲ୍ଟର କରନ୍ତୁ",
    allSkills: "ସମସ୍ତ କୌଶଳ",
    searchPlaceholder: "ଶୀର୍ଷକ କିମ୍ବା ସହର ଦ୍ୱାରା ଖୋଜନ୍ତୁ...",
    employerProfile: "ନିଯୁକ୍ତିଦାତା",
    trusted: "ବିଶ୍ୱାସଯୋଗ୍ୟ",
    waitingForDecision: "ନିଯୁକ୍ତିଦାତାଙ୍କ ପାଇଁ ଅପେକ୍ଷାରେ...",
    withdraw: "ପ୍ରତ୍ୟାହାର କରନ୍ତୁ",
    goToActive: "ସକ୍ରିୟ କାମକୁ ଯାଆନ୍ତୁ",
    confirmed: "ନିଶ୍ଚିତ",
    rejected: "ଏଥର ମନୋନୀତ ହୋଇନାହାଁନ୍ତି",
    noPending: "କୌଣସି ବକେୟା ଆବେଦନ ନାହିଁ।",
    noInvites: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ନିମନ୍ତ୍ରଣ ନାହିଁ।",
    accept: "ଗ୍ରହଣ କରନ୍ତୁ",
    decline: "ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ",
    invitedFor: "ଏଥିପାଇଁ ନିମନ୍ତ୍ରିତ",
    activeJobTitle: "ଆପଣଙ୍କ ବର୍ତ୍ତମାନର କାମ",
    callEmployer: "ନିଯୁକ୍ତିଦାତାଙ୍କୁ କଲ୍ କରନ୍ତୁ",
    uploadPhoto: "କାମର ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
    takeSelfie: "ସାଇଟରେ ସେଲ୍ଫି ନିଅନ୍ତୁ",
    markComplete: "କାମ ସମାପ୍ତ ବୋଲି ଚିହ୍ନଟ କରନ୍ତୁ",
    rateEmployer: "ନିଯୁକ୍ତିଦାତାଙ୍କୁ ରେଟ୍ କରନ୍ତୁ",
    quickTags: "ଦ୍ରୁତ ଟ୍ୟାଗ୍",
    reviewText: "ଆଉ କିଛି କହିବାକୁ ଅଛି କି? (ଇଚ୍ଛାଧୀନ)",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    noActiveJob: "ଆପଣଙ୍କର ବର୍ତ୍ତମାନ କୌଣସି ସକ୍ରିୟ କାମ ନାହିଁ।",
    findWork: "କାମ ଖୋଜନ୍ତୁ",
    title: "କାମର ଶୀର୍ଷକ",
    description: "ବର୍ଣ୍ଣନା",
    address: "ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା",
    workersNeeded: "ଆବଶ୍ୟକ ଶ୍ରମିକ",
    postJobCta: "କାମ ପୋଷ୍ଟ କରନ୍ତୁ",
    applicants: "ଆବେଦନକାରୀ",
    hire: "ନିଯୁକ୍ତ କରନ୍ତୁ",
    pass: "ଛାଡ଼ନ୍ତୁ",
    hired: "ନିଯୁକ୍ତ",
    noApplicants: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆବେଦନକାରୀ ନାହାଁନ୍ତି।",
    browseWorkers: "ଶ୍ରମିକ ଦେଖନ୍ତୁ",
    sendInvite: "ନିମନ୍ତ୍ରଣ ପଠାନ୍ତୁ...",
    completeReview: "ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ ଏବଂ ସମୀକ୍ଷା କରନ୍ତୁ",
    noActiveEmp: "କୌଣସି ସକ୍ରିୟ କାମ ନାହିଁ।",
    aadhaarVerified: "ଆଧାର ଯାଞ୍ଚ ହୋଇଛି",
    jobsPosted: "ପୋଷ୍ଟ ହୋଇଥିବା କାମ",
    jobsCompleted: "ସମାପ୍ତ ହୋଇଥିବା କାମ",
    backToList: "ପଛକୁ",
    languageToggle: "ଭାଷା",
    youAreOffline: "ଆପଣ ନିଯୁକ୍ତିଦାତାଙ୍କଠାରୁ ଲୁକ୍କାୟିତ",
    youAreOnline: "ଆପଣ ନିଯୁକ୍ତିଦାତାଙ୍କୁ ଦୃଶ୍ୟମାନ",
    confirmHire: "ଏହି ଶ୍ରମିକଙ୍କୁ ନିଯୁକ୍ତ କରିବେ କି?",
    photoSaved: "ଫଟୋ ସେଭ୍ ହେଲା",
    thanks: "ଧନ୍ୟବାଦ!",
    safeWorkplace: "ସୁରକ୍ଷିତ କାର୍ଯ୍ୟସ୍ଥଳ",
    fairPayment: "ନ୍ୟାୟ୍ୟ ପ୍ରଦାନ",
    onTime: "ସମୟରେ ପ୍ରଦାନ କରନ୍ତି",
    respectful: "ସମ୍ମାନଜନକ",
    skilled: "କୌଶଳୀ",
    punctual: "ସମୟନିଷ୍ଠ",
    polite: "ନମ୍ର",
    neatWork: "ପରିଷ୍କାର କାମ",
  },
  pa: {
    appName: "ਰੋਜ਼ਗਾਰ ਮਿੱਤਰ",
    tagline: "ਭਰੋਸੇਯੋਗ ਕੰਮ, ਸਹੀ ਮਜ਼ਦੂਰੀ",
    login: "ਲਾਗਇਨ",
    register: "ਰਜਿਸਟਰ",
    username: "ਯੂਜ਼ਰਨੇਮ",
    password: "ਪਾਸਵਰਡ",
    name: "ਪੂਰਾ ਨਾਮ",
    phone: "ਫ਼ੋਨ",
    city: "ਸ਼ਹਿਰ",
    area: "ਇਲਾਕਾ",
    skill: "ਹੁਨਰ",
    experience: "ਤਜਰਬਾ (ਸਾਲ)",
    company: "ਕੰਪਨੀ ਦਾ ਨਾਮ",
    iAmA: "ਮੈਂ ਇੱਕ",
    worker: "ਕਾਮਾ",
    employer: "ਰੁਜ਼ਗਾਰਦਾਤਾ",
    continue: "ਜਾਰੀ ਰੱਖੋ",
    demoAccounts: "ਡੈਮੋ ਖਾਤੇ (ਬਦਲਣ ਲਈ ਟੈਪ ਕਰੋ)",
    search: "ਕੰਮ ਲੱਭੋ",
    active: "ਚਾਲੂ",
    pending: "ਬਕਾਇਆ",
    invites: "ਸੱਦੇ",
    postJob: "ਕੰਮ ਪੋਸਟ ਕਰੋ",
    myJobs: "ਮੇਰੇ ਕੰਮ",
    workers: "ਕਾਮੇ",
    activeJobs: "ਚਾਲੂ ਕੰਮ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    history: "ਕੰਮ ਦਾ ਇਤਿਹਾਸ",
    reviews: "ਸਮੀਖਿਆਵਾਂ",
    logout: "ਲਾਗਆਉਟ",
    availability: "ਮੈਂ ਕੰਮ ਲਈ ਉਪਲਬਧ ਹਾਂ",
    urgentNow: "ਮੈਂ ਹੁਣੇ ਉਪਲਬਧ ਹਾਂ",
    urgentActive: "🟢 ਲਾਈਵ — 8 ਘੰਟੇ ਦੀ ਪਲਸ ਚਾਲੂ",
    yourPassport: "ਤੁਹਾਡਾ ਵਰਕ ਪਾਸਪੋਰਟ",
    reliabilityScore: "ਭਰੋਸੇਯੋਗਤਾ ਸਕੋਰ",
    verifiedJobs: "ਤਸਦੀਕਸ਼ੁਦਾ ਕੰਮ",
    avgRating: "ਔਸਤ ਰੇਟਿੰਗ",
    totalEarned: "ਕੁੱਲ ਕਮਾਈ",
    uniqueEmployers: "ਵੱਖ-ਵੱਖ ਰੁਜ਼ਗਾਰਦਾਤਾ",
    repeatEmployers: "ਵਾਰ-ਵਾਰ ਬੁਲਾਉਣ ਵਾਲੇ",
    completionRate: "ਮੁਕੰਮਲ ਹੋਣ ਦੀ ਦਰ",
    shareWhatsApp: "ਵਟਸਐਪ ਤੇ ਸਾਂਝਾ ਕਰੋ",
    applyNow: "ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ",
    applied: "ਅਰਜ਼ੀ ਦਿੱਤੀ",
    spotsLeft: "ਥਾਂਵਾਂ ਬਾਕੀ",
    deadline: "ਆਖਰੀ ਮਿਤੀ",
    budget: "ਬਜਟ",
    noJobs: "ਤੁਹਾਡੇ ਫਿਲਟਰ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਕੋਈ ਕੰਮ ਨਹੀਂ।",
    filterBySkill: "ਹੁਨਰ ਅਨੁਸਾਰ ਫਿਲਟਰ ਕਰੋ",
    allSkills: "ਸਾਰੇ ਹੁਨਰ",
    searchPlaceholder: "ਸਿਰਲੇਖ ਜਾਂ ਸ਼ਹਿਰ ਦੁਆਰਾ ਖੋਜੋ...",
    employerProfile: "ਰੁਜ਼ਗਾਰਦਾਤਾ",
    trusted: "ਭਰੋਸੇਯੋਗ",
    waitingForDecision: "ਰੁਜ਼ਗਾਰਦਾਤਾ ਦੀ ਉਡੀਕ...",
    withdraw: "ਵਾਪਸ ਲਓ",
    goToActive: "ਚਾਲੂ ਕੰਮ ਤੇ ਜਾਓ",
    confirmed: "ਪੁਸ਼ਟੀ ਹੋਈ",
    rejected: "ਇਸ ਵਾਰ ਨਹੀਂ ਚੁਣਿਆ ਗਿਆ",
    noPending: "ਕੋਈ ਬਕਾਇਆ ਅਰਜ਼ੀ ਨਹੀਂ।",
    noInvites: "ਹਾਲੇ ਕੋਈ ਸੱਦਾ ਨਹੀਂ।",
    accept: "ਸਵੀਕਾਰ ਕਰੋ",
    decline: "ਇਨਕਾਰ ਕਰੋ",
    invitedFor: "ਇਸ ਲਈ ਸੱਦਾ",
    activeJobTitle: "ਤੁਹਾਡਾ ਮੌਜੂਦਾ ਕੰਮ",
    callEmployer: "ਰੁਜ਼ਗਾਰਦਾਤਾ ਨੂੰ ਕਾਲ ਕਰੋ",
    uploadPhoto: "ਕੰਮ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    takeSelfie: "ਸਾਈਟ ਤੇ ਸੈਲਫੀ ਲਓ",
    markComplete: "ਕੰਮ ਮੁਕੰਮਲ ਵਜੋਂ ਨਿਸ਼ਾਨਬੱਧ ਕਰੋ",
    rateEmployer: "ਰੁਜ਼ਗਾਰਦਾਤਾ ਨੂੰ ਰੇਟ ਕਰੋ",
    quickTags: "ਤੁਰੰਤ ਟੈਗ",
    reviewText: "ਹੋਰ ਕੁਝ ਕਹਿਣਾ ਹੈ? (ਵਿਕਲਪਿਕ)",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    noActiveJob: "ਤੁਹਾਡੇ ਕੋਲ ਹੁਣ ਕੋਈ ਚਾਲੂ ਕੰਮ ਨਹੀਂ ਹੈ।",
    findWork: "ਕੰਮ ਲੱਭੋ",
    title: "ਕੰਮ ਦਾ ਸਿਰਲੇਖ",
    description: "ਵੇਰਵਾ",
    address: "ਪੂਰਾ ਪਤਾ",
    workersNeeded: "ਲੋੜੀਂਦੇ ਕਾਮੇ",
    postJobCta: "ਕੰਮ ਪੋਸਟ ਕਰੋ",
    applicants: "ਬਿਨੈਕਾਰ",
    hire: "ਰੱਖੋ",
    pass: "ਛੱਡੋ",
    hired: "ਰੱਖਿਆ ਗਿਆ",
    noApplicants: "ਹਾਲੇ ਕੋਈ ਬਿਨੈਕਾਰ ਨਹੀਂ।",
    browseWorkers: "ਕਾਮੇ ਵੇਖੋ",
    sendInvite: "ਸੱਦਾ ਭੇਜੋ...",
    completeReview: "ਮੁਕੰਮਲ ਕਰੋ ਅਤੇ ਸਮੀਖਿਆ ਕਰੋ",
    noActiveEmp: "ਕੋਈ ਚਾਲੂ ਕੰਮ ਨਹੀਂ।",
    aadhaarVerified: "ਆਧਾਰ ਤਸਦੀਕਸ਼ੁਦਾ",
    jobsPosted: "ਪੋਸਟ ਕੀਤੇ ਕੰਮ",
    jobsCompleted: "ਮੁਕੰਮਲ ਕੀਤੇ ਕੰਮ",
    backToList: "ਵਾਪਸ",
    languageToggle: "ਭਾਸ਼ਾ",
    youAreOffline: "ਤੁਸੀਂ ਰੁਜ਼ਗਾਰਦਾਤਾਵਾਂ ਤੋਂ ਲੁਕੇ ਹੋ",
    youAreOnline: "ਤੁਸੀਂ ਰੁਜ਼ਗਾਰਦਾਤਾਵਾਂ ਨੂੰ ਦਿਖਾਈ ਦੇ ਰਹੇ ਹੋ",
    confirmHire: "ਇਸ ਕਾਮੇ ਨੂੰ ਰੱਖੀਏ?",
    photoSaved: "ਫੋਟੋ ਸੇਵ ਹੋਈ",
    thanks: "ਧੰਨਵਾਦ!",
    safeWorkplace: "ਸੁਰੱਖਿਅਤ ਕੰਮ ਵਾਲੀ ਥਾਂ",
    fairPayment: "ਸਹੀ ਭੁਗਤਾਨ",
    onTime: "ਸਮੇਂ ਤੇ ਭੁਗਤਾਨ ਕਰਦੇ ਹਨ",
    respectful: "ਸਤਿਕਾਰਯੋਗ",
    skilled: "ਹੁਨਰਮੰਦ",
    punctual: "ਸਮੇਂ ਦਾ ਪਾਬੰਦ",
    polite: "ਨਿਮਰ",
    neatWork: "ਸਾਫ਼-ਸੁਥਰਾ ਕੰਮ",
  },
  ml: {
    appName: "റോസ്ഗാർ മിത്ര",
    tagline: "വിശ്വസനീയമായ ജോലി, ന്യായമായ വേതനം",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    username: "ഉപയോക്തൃനാമം",
    password: "പാസ്‌വേഡ്",
    name: "മുഴുവൻ പേര്",
    phone: "ഫോൺ",
    city: "നഗരം",
    area: "പ്രദേശം",
    skill: "വൈദഗ്ധ്യം",
    experience: "പരിചയം (വർഷം)",
    company: "കമ്പനിയുടെ പേര്",
    iAmA: "ഞാൻ ഒരു",
    worker: "തൊഴിലാളി",
    employer: "തൊഴിൽദാതാവ്",
    continue: "തുടരുക",
    demoAccounts: "ഡെമോ അക്കൗണ്ടുകൾ (മാറ്റാൻ ടാപ്പ് ചെയ്യുക)",
    search: "ജോലി തിരയുക",
    active: "സജീവം",
    pending: "തീർപ്പാക്കാത്തത്",
    invites: "ക്ഷണങ്ങൾ",
    postJob: "ജോലി പോസ്റ്റ് ചെയ്യുക",
    myJobs: "എന്റെ ജോലികൾ",
    workers: "തൊഴിലാളികൾ",
    activeJobs: "സജീവ ജോലികൾ",
    profile: "പ്രൊഫൈൽ",
    history: "ജോലി ചരിത്രം",
    reviews: "അവലോകനങ്ങൾ",
    logout: "ലോഗ്ഔട്ട്",
    availability: "ഞാൻ ജോലിക്ക് ലഭ്യമാണ്",
    urgentNow: "ഞാൻ ഇപ്പോൾ ലഭ്യമാണ്",
    urgentActive: "🟢 ലൈവ് — 8 മണിക്കൂർ പൾസ് സജീവം",
    yourPassport: "നിങ്ങളുടെ വർക്ക് പാസ്‌പോർട്ട്",
    reliabilityScore: "വിശ്വാസ്യതാ സ്‌കോർ",
    verifiedJobs: "സ്ഥിരീകരിച്ച ജോലികൾ",
    avgRating: "ശരാശരി റേറ്റിംഗ്",
    totalEarned: "ആകെ വരുമാനം",
    uniqueEmployers: "വ്യത്യസ്ത തൊഴിൽദാതാക്കൾ",
    repeatEmployers: "ആവർത്തിച്ച് വിളിക്കുന്ന തൊഴിൽദാതാക്കൾ",
    completionRate: "പൂർത്തീകരണ നിരക്ക്",
    shareWhatsApp: "വാട്ട്‌സ്ആപ്പിൽ പങ്കിടുക",
    applyNow: "ഇപ്പോൾ അപേക്ഷിക്കുക",
    applied: "അപേക്ഷിച്ചു",
    spotsLeft: "സ്ഥലങ്ങൾ ബാക്കി",
    deadline: "അവസാന തീയതി",
    budget: "ബജറ്റ്",
    noJobs: "നിങ്ങളുടെ ഫിൽട്ടറുമായി പൊരുത്തപ്പെടുന്ന ജോലികളില്ല.",
    filterBySkill: "വൈദഗ്ധ്യം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
    allSkills: "എല്ലാ വൈദഗ്ധ്യങ്ങളും",
    searchPlaceholder: "ശീർഷകം അല്ലെങ്കിൽ നഗരം ഉപയോഗിച്ച് തിരയുക...",
    employerProfile: "തൊഴിൽദാതാവ്",
    trusted: "വിശ്വസനീയമായ",
    waitingForDecision: "തൊഴിൽദാതാവിനെ കാത്തിരിക്കുന്നു...",
    withdraw: "പിൻവലിക്കുക",
    goToActive: "സജീവ ജോലിയിലേക്ക് പോകുക",
    confirmed: "സ്ഥിരീകരിച്ചു",
    rejected: "ഇത്തവണ തിരഞ്ഞെടുത്തിട്ടില്ല",
    noPending: "തീർപ്പാക്കാത്ത അപേക്ഷകളില്ല.",
    noInvites: "ഇതുവരെ ക്ഷണങ്ങളൊന്നുമില്ല.",
    accept: "സ്വീകരിക്കുക",
    decline: "നിരസിക്കുക",
    invitedFor: "ഇതിനായി ക്ഷണിച്ചു",
    activeJobTitle: "നിങ്ങളുടെ നിലവിലെ ജോലി",
    callEmployer: "തൊഴിൽദാതാവിനെ വിളിക്കുക",
    uploadPhoto: "ജോലിയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    takeSelfie: "സൈറ്റിൽ സെൽഫി എടുക്കുക",
    markComplete: "ജോലി പൂർത്തിയായി അടയാളപ്പെടുത്തുക",
    rateEmployer: "തൊഴിൽദാതാവിനെ റേറ്റ് ചെയ്യുക",
    quickTags: "ദ്രുത ടാഗുകൾ",
    reviewText: "വേറെ എന്തെങ്കിലും പറയാനുണ്ടോ? (ഐച്ഛികം)",
    submit: "സമർപ്പിക്കുക",
    noActiveJob: "നിങ്ങൾക്ക് ഇപ്പോൾ സജീവ ജോലിയില്ല.",
    findWork: "ജോലി കണ്ടെത്തുക",
    title: "ജോലിയുടെ പേര്",
    description: "വിവരണം",
    address: "പൂർണ്ണ വിലാസം",
    workersNeeded: "ആവശ്യമായ തൊഴിലാളികൾ",
    postJobCta: "ജോലി പോസ്റ്റ് ചെയ്യുക",
    applicants: "അപേക്ഷകർ",
    hire: "നിയമിക്കുക",
    pass: "ഒഴിവാക്കുക",
    hired: "നിയമിച്ചു",
    noApplicants: "ഇതുവരെ അപേക്ഷകരില്ല.",
    browseWorkers: "തൊഴിലാളികളെ കാണുക",
    sendInvite: "ക്ഷണം അയയ്ക്കുക...",
    completeReview: "പൂർത്തിയാക്കി അവലോകനം ചെയ്യുക",
    noActiveEmp: "സജീവ ജോലികളില്ല.",
    aadhaarVerified: "ആധാർ സ്ഥിരീകരിച്ചു",
    jobsPosted: "പോസ്റ്റ് ചെയ്ത ജോലികൾ",
    jobsCompleted: "പൂർത്തിയാക്കിയ ജോലികൾ",
    backToList: "തിരികെ",
    languageToggle: "ഭാഷ",
    youAreOffline: "നിങ്ങൾ തൊഴിൽദാതാക്കളിൽ നിന്ന് മറഞ്ഞിരിക്കുന്നു",
    youAreOnline: "നിങ്ങൾ തൊഴിൽദാതാക്കൾക്ക് ദൃശ്യമാണ്",
    confirmHire: "ഈ തൊഴിലാളിയെ നിയമിക്കണോ?",
    photoSaved: "ഫോട്ടോ സേവ് ചെയ്തു",
    thanks: "നന്ദി!",
    safeWorkplace: "സുരക്ഷിതമായ ജോലിസ്ഥലം",
    fairPayment: "ന്യായമായ പണമടയ്ക്കൽ",
    onTime: "സമയത്ത് പണം നൽകുന്നു",
    respectful: "ബഹുമാനത്തോടെ",
    skilled: "വൈദഗ്ധ്യമുള്ള",
    punctual: "കൃത്യനിഷ്ഠയുള്ള",
    polite: "വിനയമുള്ള",
    neatWork: "വൃത്തിയുള്ള ജോലി",
  },
  as: {
    appName: "ৰোজগাৰ মিত্ৰ",
    tagline: "বিশ্বাসযোগ্য কাম, ন্যায্য বেতন",
    login: "লগইন",
    register: "ৰেজিষ্ট্ৰেশ্যন",
    username: "ব্যৱহাৰকাৰী নাম",
    password: "পাছৱৰ্ড",
    name: "সম্পূৰ্ণ নাম",
    phone: "ফোন",
    city: "চহৰ",
    area: "অঞ্চল",
    skill: "দক্ষতা",
    experience: "অভিজ্ঞতা (বছৰ)",
    company: "কোম্পানীৰ নাম",
    iAmA: "মই এজন",
    worker: "শ্ৰমিক",
    employer: "নিয়োগকৰ্তা",
    continue: "আগবাঢ়ক",
    demoAccounts: "ডেমো একাউণ্ট (সলনি কৰিবলৈ টিপক)",
    search: "কাম বিচাৰক",
    active: "সক্ৰিয়",
    pending: "বাকী",
    invites: "নিমন্ত্ৰণ",
    postJob: "কাম পোষ্ট কৰক",
    myJobs: "মোৰ কাম",
    workers: "শ্ৰমিকসকল",
    activeJobs: "সক্ৰিয় কাম",
    profile: "প্ৰ'ফাইল",
    history: "কামৰ ইতিহাস",
    reviews: "পৰ্যালোচনা",
    logout: "লগআউট",
    availability: "মই কামৰ বাবে উপলব্ধ",
    urgentNow: "মই এতিয়াই উপলব্ধ",
    urgentActive: "🟢 লাইভ — 8 ঘণ্টা পালচ্ চলি আছে",
    yourPassport: "আপোনাৰ কাম পাছপৰ্ট",
    reliabilityScore: "নিৰ্ভৰযোগ্যতা স্ক'ৰ",
    verifiedJobs: "সত্যাপিত কাম",
    avgRating: "গড় ৰেটিং",
    totalEarned: "মুঠ উপাৰ্জন",
    uniqueEmployers: "পৃথক নিয়োগকৰ্তা",
    repeatEmployers: "বাৰে বাৰে মতা নিয়োগকৰ্তা",
    completionRate: "সমাপ্তিৰ হাৰ",
    shareWhatsApp: "হোৱাটছএপত শ্বেয়াৰ কৰক",
    applyNow: "এতিয়াই আবেদন কৰক",
    applied: "আবেদন কৰা হৈছে",
    spotsLeft: "ঠাই বাকী",
    deadline: "শেষ তাৰিখ",
    budget: "বাজেট",
    noJobs: "আপোনাৰ ফিল্টাৰৰ সৈতে মিল থকা কাম নাই।",
    filterBySkill: "দক্ষতা অনুসৰি ফিল্টাৰ কৰক",
    allSkills: "সকলো দক্ষতা",
    searchPlaceholder: "শিৰোনাম বা চহৰৰ দ্বাৰা বিচাৰক...",
    employerProfile: "নিয়োগকৰ্তা",
    trusted: "বিশ্বাসযোগ্য",
    waitingForDecision: "নিয়োগকৰ্তাৰ বাবে অপেক্ষা...",
    withdraw: "প্ৰত্যাহাৰ কৰক",
    goToActive: "সক্ৰিয় কামলৈ যাওক",
    confirmed: "নিশ্চিত কৰা হৈছে",
    rejected: "এইবাৰ নিৰ্বাচিত হোৱা নাই",
    noPending: "কোনো বাকী থকা আবেদন নাই।",
    noInvites: "এতিয়ালৈকে কোনো নিমন্ত্ৰণ নাই।",
    accept: "গ্ৰহণ কৰক",
    decline: "নাকচ কৰক",
    invitedFor: "ইয়াৰ বাবে নিমন্ত্ৰিত",
    activeJobTitle: "আপোনাৰ বৰ্তমানৰ কাম",
    callEmployer: "নিয়োগকৰ্তাক কল কৰক",
    uploadPhoto: "কামৰ ফটো আপলোড কৰক",
    takeSelfie: "ছাইটত ছেলফি লওক",
    markComplete: "কাম সম্পূৰ্ণ বুলি চিহ্নিত কৰক",
    rateEmployer: "নিয়োগকৰ্তাক ৰেট কৰক",
    quickTags: "দ্ৰুত টেগ",
    reviewText: "আন কিবা কব লাগে নেকি? (ঐচ্ছিক)",
    submit: "দাখিল কৰক",
    noActiveJob: "আপোনাৰ এতিয়া কোনো সক্ৰিয় কাম নাই।",
    findWork: "কাম বিচাৰক",
    title: "কামৰ শিৰোনাম",
    description: "বিৱৰণ",
    address: "সম্পূৰ্ণ ঠিকনা",
    workersNeeded: "প্ৰয়োজনীয় শ্ৰমিক",
    postJobCta: "কাম পোষ্ট কৰক",
    applicants: "আবেদনকাৰী",
    hire: "নিয়োগ কৰক",
    pass: "এৰি দিয়ক",
    hired: "নিয়োগ কৰা হৈছে",
    noApplicants: "এতিয়ালৈকে কোনো আবেদনকাৰী নাই।",
    browseWorkers: "শ্ৰমিক চাওক",
    sendInvite: "নিমন্ত্ৰণ পঠিয়াওক...",
    completeReview: "সম্পূৰ্ণ কৰক আৰু পৰ্যালোচনা কৰক",
    noActiveEmp: "কোনো সক্ৰিয় কাম নাই।",
    aadhaarVerified: "আধাৰ সত্যাপিত",
    jobsPosted: "পোষ্ট কৰা কাম",
    jobsCompleted: "সম্পূৰ্ণ কৰা কাম",
    backToList: "উভতি যাওক",
    languageToggle: "ভাষা",
    youAreOffline: "আপুনি নিয়োগকৰ্তাসকলৰ পৰা লুকাই আছে",
    youAreOnline: "আপুনি নিয়োগকৰ্তাসকলৰ ওচৰত দৃশ্যমান",
    confirmHire: "এই শ্ৰমিকজনক নিয়োগ কৰিবনে?",
    photoSaved: "ফটো ছেভ কৰা হ'ল",
    thanks: "ধন্যবাদ!",
    safeWorkplace: "সুৰক্ষিত কৰ্মস্থল",
    fairPayment: "ন্যায্য পৰিশোধ",
    onTime: "সময়মতে পৰিশোধ কৰে",
    respectful: "সন্মানীয়",
    skilled: "দক্ষ",
    punctual: "সময়ানুবৰ্তী",
    polite: "বিনয়ী",
    neatWork: "চাফা কাম",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    const saved = localStorage.getItem("rm_lang");
    return saved && STRINGS[saved] ? saved : "en";
  });

  const setLang = (code) => {
    if (!STRINGS[code]) return;
    localStorage.setItem("rm_lang", code);
    setLangState(code);
  };

  // Kept for any old call sites — cycles English <-> Hindi like before.
  const toggle = () => setLang(lang === "en" ? "hi" : "en");

  // Fall back to English for any key a given language is missing,
  // so a partially-translated language never renders blank text.
  const t = { ...STRINGS.en, ...STRINGS[lang] };

  return (
    <LangContext.Provider value={{ lang, setLang, toggle, t, languages: LANGUAGES }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
